ES6 e além
cez-aug/You-Dont-Know-JS pull request #131
Opened 2016-10-31 02:21 UTC by brunapereira

# Antes de enviar seu Pull Request

Faça o check abaixo para ver se o PR está no melhor padrão possível. 
Note que o conteúdo enviado será revisado antes de ser aceito, em geral blocos maiores de tradução levarão mais tempo
para serem aceitos (veja #68). A qualidade do material é um compromisso nosso.

**Nota:** Não deixe de marcar o último checkbox dessa lista **caso sua issue seja a última parte do capítulo traduzido**. Ao determinar no título "Nome_do_seu_commit, **close #XX**", você estará utilizando [palavras-chave do GitHub](https://help.github.com/articles/closing-issues-via-commit-messages/), referenciando diretamente a `issue` que retorna se o trabalho está pronto ou não. Isso faz a issue ser fechada automaticamente com a aprovação do seu `commit`, **caso o seu pull request signifique o término de um livro.**

- [ ] Verifique se os jargões estão coerentes com o [WORDREFERENCE](WORDREFERENCE.md)
- [ ] Revise a tradução com carinho :two_hearts: -- seu nome constará na parte que você traduziu.
- [ ] Ao terminar sua parte da tradução, faça um Pull `Request` para o `branch` `portuguese-translation`.
- [ ] Caso o `Pull Request` for o último (finalização de capítulo), use o número da `issue` como referência e faça uso [dessas keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

2016-10-31 02:30 UTC, brunapereira commented on es6 & beyond/ch6.md
> +ES6 adicional diversos utilitários matemáticos que preenchem buracos ou ajudam com operações comuns. Todos podem ser manualmente calculados, mas a maioria está agora definido nativamente, então em al
"ES6 adiciona... mas a maioria está agora definida nativamente,..... em alguns casos o motor do JS pode otimizar a performance

2016-11-10 19:31 UTC, cezaraugusto commented
@brunapereira essa parte é _work in progress_ ou está ok para revisāo?

2016-11-29 22:10 UTC, brunapereira commented
@cezaraugusto Ainda faltam algumas correções, que são os meus próprios comentários ali. Mas a ideia era já ir recebendo feedbacks enquanto isso.

2016-11-29 22:27 UTC, brunapereira commented
@cezaraugusto agora está pronto para revisão!

2016-11-29 22:32 UTC, brunapereira commented
Aqui vão algumas palavras que eu não traduzi e talvez deveríamos colocar no dicionário de jargões:

Bind / binding
Polyfilled
Helper
Non-enumerable
Non-owned
Float
Shim

2016-12-17 17:06 UTC, cezaraugusto requested changes
Ficou perfeito. Fiz dois comentarios: um sobre um trecho que foi "pulado" na traducao, e outro pra clarear a leitura.

2016-12-17 17:06 UTC, cezaraugusto commented on es6 & beyond/ch6.md
>  An "array-like object" in JavaScript is an object that has a `length` property on it, specifically with an integer value of zero or higher.
Um objeto "array-like" em JavaScript é um objeto que tem a propriedade `length` especificamente com um valor inteiro, igual ou maior que zero.

2016-12-17 17:06 UTC, cezaraugusto commented on es6 & beyond/ch6.md
> +ES6 adiciona `Object.assign(..)`, que é uma versão simplificada desses algoritmos. O primeiro argumento é o *alvo*, e quaisquer outros argumentos passados são *origens*, que vão ser processadas em um
No primeiro "origens", pode colocar entre parenteses (source):

passados são *origens* (sources), ...

2016-12-17 17:07 UTC, cezaraugusto commented
Sobre as referencias, fique a vontade para inserir no dicionário as palavras que você achar necessárias. Dessa lista, todas essas sao validas para colocar la, mesmo as que irao permanecer na forma original. Assim vai ficando mais facil nas proximas traducoes o que deve/nao deve ser inserido. Obrigado!!

2016-12-17 23:31 UTC, brunapereira commented
@cezaraugusto prontinho 😄

2016-12-18 02:12 UTC, cezaraugusto commented
++ obrigado!

2016-12-18 02:13 UTC, cezaraugusto approved these changes

2016-12-18 02:13 UTC, merged