Types & Grammar (Tipos e Gramática) - Capítulo 3
cez-aug/You-Dont-Know-JS pull request #140
Opened 2017-02-17 22:41 UTC by thiamsantos

Ref #11

2017-02-17 23:36 UTC, thiamsantos commented on types & grammar/ch3.md
> +Mas para os outros tipos primitivos como `string`, `number`, e `boolean`, outra coisa acontece, que geralmente é chamado de "boxing" (veja a próxima seção "Boxing Wrappers"):
Eu não consegui achar uma tradução apropriada para "boxing" e "Boxing Wrappers". Alguma sugestão?

2017-02-17 23:38 UTC, thiamsantos commented on types & grammar/ch3.md
> +Nesse trecho de código, cada um dos tipos primitivos simples são automaticamente encaixotados em seus respectivos objetos que os envolvem, é por isso que `"String"`, `"Number"`, e `"Boolean"` são rev
Talvez "boxed" fosse melhor traduzido com encapsulado em vez de encaixotado? O que acham?

2017-02-18 01:49 UTC, gabsprates commented on types & grammar/ch3.md
> +Nesse trecho de código, cada um dos tipos primitivos simples são automaticamente encaixotados em seus respectivos objetos que os envolvem, é por isso que `"String"`, `"Number"`, e `"Boolean"` são rev
Que tal "embalados"?

2017-02-23 03:13 UTC, cezaraugusto commented on types & grammar/ch3.md
> +Mas para os outros tipos primitivos como `string`, `number`, e `boolean`, outra coisa acontece, que geralmente é chamado de "boxing" (veja a próxima seção "Boxing Wrappers"):
podemos manter o termo original. Não consigo pensar em um modelo melhor. _Boxing_ me parece bem intuitivo e _wrapper_ me parece um termo já consagrado (assim como _loop_, _array_, etc).

2017-02-24 15:16 UTC, thiamsantos commented on types & grammar/ch3.md
> +O problema é que você criou um object wrapper ao redor o valor `false`, mas os próprios objetos são "truthy" (veja o Capítulo 4), então o uso do objeto se comporta de maneira oposta ao uso do valor `
Essa frase ficou muito estranha. Mas eu não consegui achar nenhuma maneira de traduzir sem alterar o sentido das palavras. Alguma ideia?

2017-02-24 17:05 UTC, gmsecrieru commented on types & grammar/ch3.md
> +O problema é que você criou um object wrapper ao redor o valor `false`, mas os próprios objetos são "truthy" (veja o Capítulo 4), então o uso do objeto se comporta de maneira oposta ao uso do valor `
Que tal "O problema é que você criou um objeto _wrapper_ ao redor do valor `false`, mas objetos são "truthy" por natureza (ver Capítulo 4), portanto o uso deste objeto provê um comportamento oposto ao obtido com o a utilização direta do valor `false`, o que de fato representa o oposto do que normalmente se esperaria."?

2017-02-24 21:13 UTC, thiamsantos commented on types & grammar/ch3.md
> +O problema é que você criou um object wrapper ao redor o valor `false`, mas os próprios objetos são "truthy" (veja o Capítulo 4), então o uso do objeto se comporta de maneira oposta ao uso do valor `
Muito obrigado @gmsecrieru, eu vou seguir a sua sugestão. Acho que falta eu parar tentar traduzir as palavras e focar nas ideias completas para transmitir o sentido de maneira simples.

2017-03-04 23:53 UTC, thiamsantos commented on types & grammar/ch3.md
> +Se você está sacudindo a sua cabeça ou rolando os seus olho agora, você não está sozinho!
Achei melhor deixar sem a expressão "Shrugs" porque eu não encontrei uma tradução boa. ¯\_(ツ)_/¯

2017-03-12 13:41 UTC, cezaraugusto commented
@thiamsantos como estamos? pronto pra revisao? ok se nao estiver

2017-03-12 14:05 UTC, thiamsantos commented
@cezaraugusto faltam 80 linhas, vou tentar terminar hoje para já poder começar a revisão.

2017-03-12 15:48 UTC, thiamsantos commented
@cezaraugusto a tradução foi concluído. A revisão já pode ser iniciada.

2017-03-17 13:59 UTC, gmsecrieru requested changes
Não consegui revisar todo, faltou tempo! Posso seguir assim que possível, mas já apontei algumas coisas que seria bacana corrigirmos.

Muito obrigado, @thiamsantos !

2017-03-17 13:59 UTC, gmsecrieru commented on types & grammar/ch3.md
> +**Nota:** No momento da escrita, a última versão do Chrome imprime algo assim: `String {0: "a", 1: "b", 2: "c", length: 3, [[PrimitiveValue]]: "abc"}`. Mas versões antigas do Chrome costumavam imprim
"(...) estão sujeitos à ~ráida~**rápida**"

2017-03-17 13:59 UTC, gmsecrieru commented on types & grammar/ch3.md
> +Você vai notar de que não há nenhum construtor `Null()` ou `Undefined()`, mas mesmo assim `"Null"` e `"Undefined"` são o valores `[[Class]]` internos expostos.
"(...) são o**s** valores internos para `[[Class]]` expostos"

2017-03-17 13:59 UTC, gmsecrieru commented on types & grammar/ch3.md
> +**Nota:** O comportamento de `toString()` e `[[Class]]` ilustrado aqui mudou um pouco do ES5 para o ES6, mas nós cobrimos esses detalhos no título *ES6 & Beyond* dessa série.
"(...) no título *ES6 e Além* dessa série"

2017-03-17 13:59 UTC, gmsecrieru commented on types & grammar/ch3.md
> +Estes objetos que envolvem os tipos primitos tem um propósito muito importante. Tipos primitivos não tem propriedades ou métodos, então para acessar `.length` ou `.toString()` você precisa que um obj
Que tal "(...) *encaixotar* (também conhecido como envolver) os ~tipos~**valores**, permitindo esta forma de acesso" ?

2017-03-17 13:59 UTC, gmsecrieru commented on types & grammar/ch3.md
> +Há algumas pegadinhas quando se usa object wrappers diretamente que você precisa estar ciente caso você *escolha* sempre usá-los.
"(...) ciente caso você **algum dia** *escolha* ~sempre usá-los~ **utilizá-los**"

2017-03-17 13:59 UTC, gmsecrieru commented on types & grammar/ch3.md
> +Um array que não tem valores explicitos em seus slots, mas tem uma propiedade `length` que *implica* que os slots existam, é um tipo exótico de estrutura de dado no JS com alguns comportamentos muito
"Um array que não tem valores expl~i~**í**citos em ~seus~**suas** ~slots~**posições** (...) que *implica* que ~o~**a**s ~slots~**posições** existem, (...) estrutura de dado**s** no JS (...)"

2017-03-17 13:59 UTC, gmsecrieru commented on types & grammar/ch3.md
> +**Nota:** Um array com pelo menos um "slot vazio" é comumente chamado de "sparse array".
"(...) pelo menos um**a** ~"slot vazio"~**"posição vazia"** é comumente chamado de ~"sparse array"~**"array escasso"**

2017-03-17 13:59 UTC, gmsecrieru commented on types & grammar/ch3.md
> +A serialização de `a` no Chrome é (no tempo da escrita): `[ undefined x 3 ]`. **Isso é realmente triste**. O que implica que há três valores `undefined` nos slots deste array, quando na verdade os sl
"(...) n~o~**a**s ~slots~**posições** deste array, quando na verdade ~os slots~**as posições** não existem (também chamado de ~"slots vazios"~**"posições vazias"** "

2017-03-17 13:59 UTC, gmsecrieru commented on types & grammar/ch3.md
> +**Nota:** Como você pode ver com o `c` deste exemplo, slots vazios no array podem acontecer após a criação do array. Mudando o `length` de um array para um valor acima do número de slots definidos, v
"(...) ~~slots vazios~~**posições vazias** (...)  acima do número de ~slots~**posições** definid~o~**a**s, você implicitamente introduz ~slots~**posições** vazi~o~**a**s. (...) introduziria um**a** ~slot~**posição** vazi~o~**a** ..."

2017-03-17 13:59 UTC, gmsecrieru commented on types & grammar/ch3.md
> +Como você pode ver, `join(..)` funciona apenas *supondo* que os slots existem e looping o valor de `length`. Seja o que for que `map(..)` faz internamente, ele (aparentemente) não faz essa suposição,
"(...) ~o~**a**s ~slots~**posições** existem e ~looping~**iterando** ~o~**até** (...), por isso os resultados d~o~**a**s ~"slots vazios"~ **"posições vazias"** (...)"

2017-03-17 13:59 UTC, gmsecrieru commented on types & grammar/ch3.md
> +Portanto, se você quer *na realidade* criar um array de valores `undefined` reais (não apenas "slots vazios"), como você pode fazer isso (além de manualmente)?
~"slots vazios"~**"posições vazias"**

2017-03-17 13:59 UTC, gmsecrieru commented on types & grammar/ch3.md
> +Então, `Array.apply(..)` está chamando a  função `Array(..)` e espalhando os valores (do objeto `{ length: 3 }`) como seu argumento.
Tem um espaço duplo "(...) está chamando a função (...)"

2017-03-17 13:59 UTC, gmsecrieru commented on types & grammar/ch3.md
> +Para cada índice, ele retira aquela chave do objeto. Então se o parâmetro objeto-array for chamado de `arr` internamente dentro da função `apply(..)`, o acesso à propriedade seria efetivamente `arr[0
"(...), ele ~retira~**busca** aquela chave do objeto (...)"

2017-03-18 00:56 UTC, thiamsantos commented
@gmsecrieru eu vou tentar fazer as correções amanhã

2017-03-18 18:34 UTC, gmsecrieru requested changes
Revisão finalizada

2017-03-18 18:34 UTC, gmsecrieru commented on types & grammar/ch3.md
> +Em outras palavras, acaba-se chamando `Array(..)` basicamente dessa forma: `Array(undefined,undefined,undefined)`, que é como nós acabamos com um array preenchido com valores `undefined`, e não apena
" (...) aquel~e~**a**s (louc~o~**a**s) ~slots~**posições** vazi~o~**a**s"

2017-03-18 18:34 UTC, gmsecrieru commented on types & grammar/ch3.md
> +Enquanto `Array.apply( null, { length: 3 } )` é uma estranha e verbosa de criar um array preenchido com valores `undefined`, é muito melhor e mais confiável que o que se consegue com os autodestrutiv
"(...) é uma **forma** estranha e verbosa de criar um array (...) ~o~**a**s autodestrutiv~o~**a**s ~slots~**posições** vazi~o~**a**s"

2017-03-18 18:34 UTC, gmsecrieru commented on types & grammar/ch3.md
> +Concluindo: **nunca, sobre nenhuma circunstância**, você deve intencionalmente criar e usar esse arrays com exóticos slots vazios. Apenas não faça isso. Eles são esquisitos.
"(...) ~sobre~**sob** nenhuma circunstância (...) com ~slots~**posições** vazi~o~**a**s"

2017-03-18 18:34 UTC, gmsecrieru commented on types & grammar/ch3.md
> +Os construtores `Object(..)`/`Function(..)`/`RegExp(..)` também são geralmente opcionais ( e portanto devem ser evitados a menos que sejam especificamente chamados):
Tem um espaço extra após a abertura dos parênteses ("opcionais ( e portanto ...")

2017-03-18 18:34 UTC, gmsecrieru commented on types & grammar/ch3.md
> +Não há praticamente nenhuma razão para usar o construtor `new Object()`, especialmente porque ele obriga que você adicione as propriedades uma por um em vez de todas de uma vez usando objetos literai
"(...) propriedades uma por um**a**"

2017-03-18 18:34 UTC, gmsecrieru commented on types & grammar/ch3.md
> +Para criar um objeto de date, você precisa usar `new Date()`. O construtor `Date(..)` aceita argumentos opcionais para especificar a data/tempo a ser usado, mas se omitidos, a data/tempo atual é assu
"Para criar um objeto de dat~e~**a** (...)"

2017-03-18 18:34 UTC, gmsecrieru commented on types & grammar/ch3.md
> +Até agora a principal razão para contruir um objeto de data é obter o timestamp atual (o número de milisegundos decorridos desde 1 de janeiro de 1970). Você pode fazer isso por chamar `getTime()` em
"~Até agora a~**A** principal razão para con**s**truir um objeto de data é ... "

2017-03-18 18:34 UTC, gmsecrieru commented on types & grammar/ch3.md
> +Mas uma forma mais fácil de fazer isso é por apenas chamar a função estático definida no ES5: `Date.now()`. E para fazer um polyfill para pre-ES5 é bem fácil:
"(...) fazer isso é ~por~ apenas chamar a função estátic~o~**a** (...)"

2017-03-18 18:34 UTC, gmsecrieru commented on types & grammar/ch3.md
> +**Nota:** Se você chamar `Date()` sem `new`, irá recever uma string representando a data/tempo no momento. A forma exata dessa representação não é especificada na especificação da linguagem, mas os n
"(...) irá rece~v~**b**er"

Acho que poderíamos subsituir "especificada na especificação" por "definida na especificação", me parece soar um pouco melhor, o que acha?

2017-03-18 18:34 UTC, gmsecrieru commented on types & grammar/ch3.md
> +O construtor `Error(..)` (muito parecido com `Array()` acima) se compora da mesma maneira com a palavra-chave `new` estando presente ou não.
"(...) se compor**t**a"

2017-03-18 18:34 UTC, gmsecrieru commented on types & grammar/ch3.md
> +A principal razão para criar um objeto de erro é que ele captura o contexto da pilha de execução para dentro do objeto (na maioria dos motores JS, revelado como uma propriedade `.stack` somente de le
"(...) na maioria dos motores JS é revelado, após construído, em uma propriedade somente leitura chamada `.stack`). (...) o que facilita o *debugging* (...)"

2017-03-18 18:34 UTC, gmsecrieru commented on types & grammar/ch3.md
> +Os objetos de error geralmente tem pelo menos uma propriedade `message`, e as vezes outras propriedades (que você deve tratar como somente leitura), como `type`. No entanto, além de inspecionar a pro
"(...) de erro formatad~o~**a**"

2017-03-18 18:34 UTC, gmsecrieru commented on types & grammar/ch3.md
> +Symbols podem ser usados como nomes de propriedades, mas você não pode o valor de um symbol de seu programa, nem do console de desenvolvedor. Se você *evalute* um symbol no console de desenvolvedor,
"(...) mas você não pode **ver ou acessar** o valor de um symbol. (...) Se você ~evaluate~**avaliar** um symbol no console de desenvolvedor, o que é mostrado ~para~**parece** com (...)"

2017-03-18 18:34 UTC, gmsecrieru commented on types & grammar/ch3.md
> +Há vários symbols pré-definidos no ES6, acessado como propriedades estáticos do objeto função `Symbol`, como `Symbol.create`, `Symbol.iterator`, etc. Para usar eles, faça algo como:
"(...) acessado**s** como propriedades"

2017-03-18 18:34 UTC, gmsecrieru commented on types & grammar/ch3.md
> +Apesar de symbols não serem realmente privados (`Object.getOwnPropertySymbols(..)` reflete no objeto e revela os publicamente quase publicamente), usar eles para criar propriedades privadas é provave
"(...) reflete no objeto **e revela os symbols de forma bastante pública**), usar eles para criar propriedades privadas é **possivelmente seu principal caso de uso**. Para a maioria dos desenvolvedores, eles podem tomar o lugar de propriedades com `_` **prefixo underscore**"

2017-03-18 18:34 UTC, gmsecrieru commented on types & grammar/ch3.md
> +* `String#indexOf(..)`: encontra a posição na string de outra substring
`encontra em uma string a posição de outra substring`

2017-03-18 18:34 UTC, gmsecrieru commented on types & grammar/ch3.md
> +* `String#substr(..)`, `String#substring(..)`, and `String#slice(..)`: extrai uma parte da strsing como uma nova string
`String#substr(..)`, `String#substring(..)`, ~and~**e** `String#slice(..)` (...) ~strsing~**string**

2017-03-18 18:34 UTC, gmsecrieru commented on types & grammar/ch3.md
> +* `String#toUpperCase()` and `String#toLowerCase()`: cria uma nova string a convertendo para maiúscula ou minúscula
~and~**e**

2017-03-18 18:34 UTC, gmsecrieru commented on types & grammar/ch3.md
> +Nenhum desses métodos modifica a string *no lugar*. Modificações (como conversão de caixa ou remoção de espaços) criam um novo valor a partir do valor existente.
~no lugar~*existente*

2017-03-18 18:34 UTC, gmsecrieru commented on types & grammar/ch3.md
> +Em virtudade da delegação de prototype (veja o título *this & Prototipagem de Objetos* nesta série), qualquer qualquer string pode acessar esses métodos.
~qualquer qualquer~**qualquer**

2017-03-18 18:34 UTC, gmsecrieru commented on types & grammar/ch3.md
> +Os protypes dos outros construtores contém comportamentos apropriados a seus tipos, como `Number#toFixed(..)` (stringify um número com um número fixo de dígitos decimais) e `Array#concat(..)` (funde
~protypes~**prototypes** (...) construtores cont~é~**ê**m (...) ~stringify um número ...~**converte para string um número com uma quantidade fixa de dígitos decimais**

2017-03-18 18:34 UTC, gmsecrieru commented on types & grammar/ch3.md
> +Uma ideia particularmente ruim, você pode ainda modificar esse prototypes nativos (não apenas adicionar propriedades como você já sabe):
esse**s**

2017-03-18 18:34 UTC, gmsecrieru commented on types & grammar/ch3.md
> +// não deixe dessa forma sem estranho que coisas estranhas aconteçam!
**não deixe desta forma ou coisas estranhas podem acontecer!**

2017-03-18 18:34 UTC, gmsecrieru commented on types & grammar/ch3.md
> +#### Protótipos como padrões
Acho que devemos manter a coesão e seguir utilizando "Prototypes", ou então traduzir as outras ocorrências de "prototype(s)" para "protótipo(s)"

2017-03-18 18:34 UTC, gmsecrieru commented on types & grammar/ch3.md
> +Sendo `Function.prototype` uma função vazia, `RegExp.prototype` uma regex "vazia" (não coincidente), e `Array.prototype` um array vazio, fazem deles um bom valor "padrão" para atribuir a variáveis se
Espaço duplo entre "têm" e "um valor"

2017-03-18 19:57 UTC, thiamsantos commented on types & grammar/ch3.md
> +#### Protótipos como padrões
@gmsecrieru qual forma você prefere?
Eu particularmente acho melhor deixar prototypes.

2017-03-18 21:12 UTC, cezaraugusto commented on types & grammar/ch3.md
> +#### Protótipos como padrões
++ pra prototypes

2017-03-20 13:04 UTC, gmsecrieru requested changes

2017-03-20 13:04 UTC, gmsecrieru commented on types & grammar/ch3.md
> +Você vai notar de que não há nenhum construtor `Null()` ou `Undefined()`, mas mesmo assim `"Null"` e `"Undefined"` são o valores internos para `[[Class]]`  expostos.
"são o**s** valores ..."

2017-03-20 13:04 UTC, gmsecrieru commented on types & grammar/ch3.md
> +**Nota:** Um array com pelo menos um "posição vazia" é comumente chamado de "array escasso".
"com pelo menos um**a**"

2017-03-20 13:04 UTC, gmsecrieru commented on types & grammar/ch3.md
> +Como você pode ver, `join(..)` funciona apenas *supondo* que as posições existem existem e iterando sobre o valor de `length`. Seja o que for que `map(..)` faz internamente, ele (aparentemente) não f
"que as posições existem ~existem~ e iterando"

2017-03-20 13:04 UTC, gmsecrieru commented on types & grammar/ch3.md
> +Symbols podem ser usados como nomes de propriedades, mas você não pode ver ou acessar o valor de um symbol de seu programa, nem do console de desenvolvedor. Se você avaliar um symbol no console de de
"o que é mostrado ~parace~**parece**"

2017-03-20 13:04 UTC, gmsecrieru commented on types & grammar/ch3.md
> +Há vários symbols pré-definidos no ES6, acessados como propriedades estáticos do objeto função `Symbol`, como `Symbol.create`, `Symbol.iterator`, etc. Para usar eles, faça algo como:
"como propriedades estátic~o~**a**s"

2017-03-20 13:04 UTC, gmsecrieru commented on types & grammar/ch3.md
> +#### Prototypes como padrões
Será que o original "Prototypes as defaults" não ficaria melhor traduzido como "Prototypes como valor padrão" (ou "... valor default") ?

@cezaraugusto @gabsprates

2017-03-21 17:43 UTC, cezaraugusto commented on types & grammar/ch3.md
> +#### Prototypes como padrões
eu faria _Prototypes como valor padrão (default)_

2017-03-23 12:13 UTC, thiamsantos commented on types & grammar/ch3.md
> +#### Prototypes como padrões
Eu deixei "Prototypes como valor padrão (default)"

2017-03-23 12:18 UTC, thiamsantos commented on types & grammar/ch3.md
> +Valores que são `typeof` `"object"` (como um array) são adicionalmente marcados com uma propriedade interna `[[Class]]` (pense nisto como uma *class*ificação interna ao invés de classes da tradiciona
Aqui talvez ficasse melhor: "ao invés de classes da tradicional programação orientada a ~~classes~~ **objetos**"

2017-03-29 21:13 UTC, thiamsantos commented
Mais alguma coisa para corrigir? @cezaraugusto @gmsecrieru @gabsprates

2017-04-03 16:54 UTC, merged