ES6 & Além | Capítulo 08 - Parte 1 (#59)
cez-aug/You-Dont-Know-JS pull request #155
Opened 2017-10-10 00:12 UTC by crondinini

Pela issue #68 entendi que é para enviar um PR para cada seção. 
Aqui está a primeira.

2017-10-19 06:11 UTC, cezaraugusto commented on es6 & beyond/ch8.md
> +Ainda mais importante que isso, o comitê passará em realidade a trabalhar em uma funcionalidade de cada vez. Assim que o spec de uma funcionalidade esteja completo e todos suas excentricidades tivere
```diff
-Assim que o spec
+Assim que a especificação
```

```diff
-funcionalidade esteja completo
+funcionalidade esteja completa
```

```diff
-uma vez estejam prontas
+uma vez que estejam prontas
```

2017-10-19 06:13 UTC, cezaraugusto requested changes
@crondinini a traducao ficou muito boa, desculpe a demora. Pode editar as partes que comentei? Assim que fizer faco o merge, obrigado!

2017-10-19 10:02 UTC, crondinini commented
@cezaraugusto Obrigada! Concertei as partes que você mencionou.

2017-11-08 01:32 UTC, cezaraugusto approved these changes
oi @crondinini desculpa a demora, obrigado pela ajuda!

2017-11-08 01:32 UTC, merged