[FINALIZAÇÃO DE CAPÍTULO (#14)] Types & Grammar - Apêndice A
cez-aug/You-Dont-Know-JS pull request #156
Opened 2017-10-11 19:01 UTC by alinedmelo

# Antes de enviar seu Pull Request

Faça o check abaixo para ver se o PR está no melhor padrão possível. 
Note que o conteúdo enviado será revisado antes de ser aceito, em geral blocos maiores de tradução levarão mais tempo
para serem aceitos (veja #68). A qualidade do material é um compromisso nosso.

- [ ] Verifique se os jargões estão coerentes com o [WORDREFERENCE](WORDREFERENCE.md)
- [ ] Revise a tradução com carinho :two_hearts: -- seu nome constará na parte que você traduziu.
- [ ] Ao terminar sua parte da tradução, faça um Pull `Request` para o `branch` `portuguese-translation`.
- [ ] Caso o `Pull Request` for o último (finalização de capítulo), use o número da `issue` como referência e faça uso [dessas keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

2017-10-11 19:05 UTC, alinedmelo commented
Pessoal,

Finalizado o capítulo!

É a primeira tradução técnica que faço, então peço que me deem um feedback em caso de erros na revisão.

Obrigada. =D

2017-10-19 06:16 UTC, cezaraugusto commented
oi Aline desculpe a demora pra responder, vou revisar com calma este final de semana. Um capítulo inteiro é um feito e tanto, parabéns!

2017-10-19 15:08 UTC, alinedmelo commented
Olá Cezar,

Imagina, sem problemas. Foi finalizado esse capítulo, porém como iniciei outro capítulo, os commits entraram nesse PR também:

Metaprogramação
Nomes de Funções
Interferências
Metapropriedades
Símbolos bem conhecidos
Symbol.species
Symbol.toPrimitive
Finalização do tópico symbols

São referentes ao Cap 7 - ES6 & Além(parte 1). Como poderia fazer para criar PR's isolados de cada parte? Crio uma branch para cada uma? Desculpe a bagunça aí, tô aprendendo e esse é o primeiro projeto que contribuo.

Vlw =D

2017-10-19 22:16 UTC, cezaraugusto commented
tem muitas formas, mas acho que fazer um `cherry-pick` de cada commit seria uma forma mais "facil", mesmo que um pouquinho trabalhosa.

Uma forma legal de evitar isso no futuro é criar um novo branch toda vez que voce fizer alteracoes, mas vamos ao que interessa:

Pensei assim:

### Pra criar um novo PR com as alteracoes do outro capitulo

1. Crie um novo branch `git checkout -b <novo nome do seu branch>`
2. Vamos dar um `reset` agora, `git reset 5239f9d --hard`: isso vai parear o seu branch com o nosso. Precisamos dessa etapa pra eliminar os commits que voce ja tem. Mas de boa eles estao salvos no branch original e no github.
3. Vem aqui de novo, clica na aba "commits". Copia o SHA (aquelas letrinhas estranhas) do primeiro commit que nao percentece a esse PR.
4. Agora que copiou, vamos fazer um cherry-pick. O cherry-pick "pega" commits de um branch e "teletransporta" pra outro branch. `git cherry-pick <sha que vc pegou aqui>`
5. Repita o cherry-pick com todos os commits que pertencem a outro PR (o outro capitulo), ate pegar todos os commits
6. `git push origin <nome do seu branch que voce definiu acima>`
7. So abrir o PR :)

assim que o PR do novo branch estiver pronto com os commits que voce quer, a gente precisa vir aqui de novo pra remover os commits que nao pertencem a este PR:

### Para limpar os commits indesejados deste branch

1. `git checkout portuguese-translation` (seu branch tem o mesmo nome que o nosso)
2. Aqui no GitHub, neste PR, vai na aba "commits".
3. Copia o SHA (de novo as letras doidas) do ultimo commit que te interessa
4. Agora nos vamos dar um `reset` no ultimo commit que te interessa. Assim todos os commits que vieram depois (aqueles que pertencem a outro capitulo) serao elimiados. Pelo que entendi o ultimo commit de capitulo deste PR é o 2f9419019ad604a63b4c33c1844505a00ae27d69 (Revisão)
5. `git reset <sha doidao aqui> --hard`
6. So pra confirmar, digite `git log`. O terminal vai mostrar os ultimos commits. O primeiro da lista deve ser o commit que finaliza seu trabalho nesse PR aqui. Pra sair da tela de log digite `q`
7. agora que confirmamos, precisamos de um push force. O push force altera o historico, que no caso é o que a gente quer `git push origin portuguese-translation -f`
8. Vem aqui de novo, atualiza a aba e vai em "commits". Eles devem estar la e sem os commits que voce nao quer
9. se estiver tudo certo, me da um alo dizendo que ficou tudo legal 👍

2017-10-20 13:27 UTC, alinedmelo commented
Olá Cezar,

Obrigada, consegui resolver! Já criei uma nova branch e coloquei os commits que já havia feito lá, estou quase finalizando o capítulo e daqui uns dias mando o PR.

Valeu =D

2017-11-08 01:38 UTC, cezaraugusto commented on types & grammar/apA.md
> +Além da mecânica principal da linguagem que exploramos completamente neste livro, há vários comportamentos diferentes que seu código JS pode apresentar quando ele roda no mundo real. Se o JS estava s
```diff
-executando puro dentro do motor
+executando puramente dentro do motor
```

2017-11-08 01:39 UTC, cezaraugusto commented on types & grammar/apA.md
> +É um pouco conhecido o fato que o nome oficial da linguagem é ECMAScript (referindo-se ao conjunto de padrões ECMA que o gerencia). O que então é "JavaScript"? JavaScript é o nome comercial da lingua
Acho que essa parte poderia ser mais clara:

```diff
-É um pouco conhecido
+É um fato pouco conhecido
```

2017-11-08 01:39 UTC, cezaraugusto commented on types & grammar/apA.md
> +A especificação oficial ECMAScript inclui o "Anexo B", que discute derivações específicas da especificação oficial para os propósitos de compatibilidaded do JS nos navegadores.
```diff
-compatibilidaded
+compatibilidade
```

2017-11-08 01:43 UTC, cezaraugusto commented on types & grammar/apA.md
> +* Números Octais são permitidos, como `0123` (decimal `83`) em non-`strict mode`.
acho que a gente poderia melhorar essa parte: _"em non-`strict mode`."_ como algo do tipo _"em modo não estrito (sem utilizar o strict-mode)"_. O que acha?

2017-11-08 02:12 UTC, cezaraugusto commented on types & grammar/apA.md
> +* Números Octais são permitidos, como `0123` (decimal `83`) em non-`strict mode`.
na parte _"the ending index (noninclusive)"_, o "noninclusive" se refere  que a ultima index não se inclui na resposta (não-inclusiva ou não-inclusa). Considere:

```js
var aline = 'aline'
aline.substring(0, 2)
// retorna "al". Cada letra é um indice (index) representado por um numero
// a-l-i-n-e
// 0-1-2-3-4
// O segundo parametro (2) é um delimitador e exclui ela mesma.
// Por isso nao temos o *i* como resposta.
```

e em contrapartida:

```js
var aline = 'aline'
aline.substr(0, 2)
// tambem retorna *al*

// O primeiro parametro ainda e o indice (index - a posicao da letra na palavra), 
// entao ao pegar o *0* no nosso exemplo estamos pegando o "a".
// No caso de *.substr*, o segundo parametro (2) se refere ao tamanho da string
// (5 -- aline tem 5 letras), mas diferente de arrays (que comecam com indice 0).
// a propriedade .length comeca do numero 1. Entao ao declarar (2), ele pega os dois indices
// apos o *0*, que sao 1 e 2 (A e L).
// Se quiser testar, tente mudar o *0* para *1*, tipo aline.substr(1, 2). Ele vai retornar *li*
// porque voce determinou que a funcao deveria comecar do indice 1 (letra A) e ter um limite
// de 2 caracteres. Como o *a* é _nao-inclusivo_, ele pega o *i* e o *l*.
```

acho que a gente pode mudar `(noninclusive)` para `nao-inclusivo`.

2017-11-08 02:17 UTC, cezaraugusto commented on types & grammar/apA.md
> +* `String.prototype.substr` é bem similiar à `String.prototype.substring`, exceto que ao invés do segundo parâmetro ser o último index (noninclusive), o segundo parâmetro é o `lenght` (números de car
na parte _"the ending index (noninclusive)"_, o "noninclusive" se refere  que a ultima index não se inclui na resposta (não-inclusiva ou não-inclusa). Considere:

```js
var aline = 'aline'
aline.substring(0, 2)
// retorna "al". Cada letra é um indice (index) representado por um numero
// a-l-i-n-e
// 0-1-2-3-4
// O segundo parametro (2) é um delimitador e exclui ela mesma.
// Por isso nao temos o *i* como resposta.
```

e em contrapartida:

```js
var aline = 'aline'
aline.substr(0, 2)
// tambem retorna *al*

// O primeiro parametro é o inicio, entao 0 nao inicia nada.
// Note que nao estamos mais falando de indices aqui. Para substr temos esse caso:
// a-l-i-n-e
// 1-2-3-4-5

// No caso de *.substr*, o segundo parametro (2) se refere ao tamanho da string
// (5 -- aline tem 5 letras), mas diferente de arrays (que comecam com indice 0).
// a propriedade .length comeca do numero 1. Entao ao declarar (2), ele pega os dois indices
// apos o *0*, que sao 1 e 2 (A e L).
// Se quiser testar, tente mudar o *0* para *1*, tipo aline.substr(1, 2). Ele vai retornar *li*
// porque voce determinou que a funcao deveria comecar do indice 1 (letra A) e ter um limite
// de 2 caracteres. Como o *a* é _nao-inclusivo_, ele pega o *i* e o *l*.
```

acho que a gente pode mudar `(noninclusive)` para `nao-inclusivo`.

2017-11-08 02:19 UTC, cezaraugusto commented on types & grammar/apA.md
> +* Adições `Function.prototype`: `Function.prototype.arguments` (apelidos internos dos `arguments` do objeto) e `Function.caller` (apelidos internos de `arguments.caller`). **Observação:** `arguments`
```diff
-porssível
+possível
```

2017-11-08 02:24 UTC, cezaraugusto commented on types & grammar/apA.md
> +`a` não é só um `object`, mas um objeto global especial porque este é um elemento do DOM. Ele tem um `[[Class]]` valor interno (`"HTMLDivElement"`) diferente e vem com propriedades pré-definidas (e f
```diff
-Ele tem um `[[Class]]` valor interno (`"HTMLDivElement"`)
+Ele tem um valor interno diferente para `[[Class]]` (seu valor é `"HTMLDivElement"`) e vem ...
```

2017-11-08 02:26 UTC, cezaraugusto commented on types & grammar/apA.md
> +Outra peculiaridade já foi abordada, na seção "Objetos Falsos"(Falsy Objects) no capítulo 4: alguns objetos podem existir mas quando forçados em `boolean` eles (de forma confusa) serão forçados para
```diff
-forçados em `boolean`
-convertidos em `boolean`
```

valido tambem pro proximo "forcados" na frase

2017-11-08 02:57 UTC, cezaraugusto commented on types & grammar/apA.md
> +Um exemplo notável de um objeto global que você provavelmente vai interagir regularmente é o objeto `console` que é fornecido pelo *ambiente global* especificamente para que seu código possa interagi
objeto `console` **e suas varias funcionalidades (`log(..)`, `error(..)`, etc.)** ...

2017-11-08 02:58 UTC, cezaraugusto commented on types & grammar/apA.md
> +Objetos globais são fundamentais para tornar nosso código JS funcional em todo ambiente. Mas é importante lembrar quando você está interagindo com um objeto global e ter cuidado ao assumir seu compor
```diff
-conformiadade
+conformidade
```

2017-11-08 03:00 UTC, cezaraugusto commented on types & grammar/apA.md
> +Um exemplo notável de um objeto global que você provavelmente vai interagir regularmente é o objeto `console` que é fornecido pelo *ambiente global* especificamente para que seu código possa interagi
```diff
-por várias tarefas de relacionadas ao desenvolvimento em produção.
+para várias tarefas relacionadas ao output do desenvolvimento
``

2017-11-08 03:02 UTC, cezaraugusto commented on types & grammar/apA.md
> +Depois de quase uma semana de análise/debbug, eu encontrei que o que o site em questão tinha, enterrado profundamente em um dos seus arquivos legados, um código parecido com isso:
~~que o~~ que o site

2017-11-08 03:04 UTC, cezaraugusto commented on types & grammar/apA.md
> +O que se destaca é uma questão interessandte que, francamente, não recebe a atenção devida dos desenvolvedores JS:
interessandte -> interessante

2017-11-08 03:29 UTC, cezaraugusto requested changes
@alinedmelo fiz uns comentários, no geral ficou muito bom 👍

2017-11-08 20:58 UTC, alinedmelo commented
@cezaraugusto legal! Fiz as correções que mencionou.

Obrigada!

2017-11-16 21:29 UTC, merged