Capítulo 8: ES6 & Além #59
cez-aug/You-Dont-Know-JS pull request #165
Opened 2017-12-07 19:50 UTC by brunapereira

# Antes de enviar seu Pull Request

Faça o check abaixo para ver se o PR está no melhor padrão possível. 
Note que o conteúdo enviado será revisado antes de ser aceito, em geral blocos maiores de tradução levarão mais tempo
para serem aceitos (veja #68). A qualidade do material é um compromisso nosso.

- [ ] Verifique se os jargões estão coerentes com o [WORDREFERENCE](WORDREFERENCE.md)
- [ ] Revise a tradução com carinho :two_hearts: -- seu nome constará na parte que você traduziu.
- [ ] Ao terminar sua parte da tradução, faça um Pull `Request` para o `branch` `portuguese-translation`.
- [ ] Caso o `Pull Request` for o último (finalização de capítulo), use o número da `issue` como referência e faça uso [dessas keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

2017-12-07 21:21 UTC, alinedmelo requested changes
Olá @brunapereira, fiz alguns comentários.

Obrigada =D

2017-12-07 21:21 UTC, alinedmelo commented on es6 & beyond/ch8.md
> +Além dos seis tipos de evento nativos, você também pode ouvir e disparar eventos customizados.
```diff
- Além dos seis tipos de evento nativos
+ Além dos seis tipos de eventos nativos
```

2017-12-07 21:21 UTC, alinedmelo commented on es6 & beyond/ch8.md
> +No exemplo anterior, nós chamamos `notifier.notify(..)` com registro completo do evento de mudanças. Uma forma alternativa de colocar os registros de mudança na fila é usar o `performChange(..)`, que
```diff
- que separa o tipo de evento do resto das propriedades (via uma função callback)
+ que separa o tipo de evento do resto das propriedades de registro (via uma função callback)
```

2017-12-11 18:35 UTC, alinedmelo requested changes

2017-12-11 18:35 UTC, alinedmelo commented on es6 & beyond/ch8.md
> +Mas JS não é só ES6! Nem perto disso. Já existem algumas novas funcionalidades em vários estágios do desenvolvimento para os temos "além do ES6". Nrsse capítulo, nós brevemente vimos alguns dos mais
```diff
- vários estágios do desenvolvimento para os temos "além do ES6"
+ vários estágios de desenvolvimento para os tempos de "além do ES6"

- Nrsse capítulo
+ Nesse capítulo
```

2017-12-11 18:42 UTC, alinedmelo requested changes

2017-12-11 18:42 UTC, alinedmelo commented on es6 & beyond/ch8.md
> +Nós cobrimos Instrução Única, Múltiplos Dados (SIMD - Single Instruction, Multiple Data) em mais detalhes no título *Async e Performance* dessa série, mas essa é uma rápida menção, já que é uma das f
```diff
- Nós cobrimos Instrução Única, Múltiplos Dados
+ Nós abordamos a Instrução Única, Dados Múltiplos

```

2017-12-11 18:45 UTC, alinedmelo commented
Olá @brunapereira, fiz mais alguns comentário dos capítulos que não tinha visto antes. De resto tá ótimo! feita essas correções dou o merge. =D

2017-12-11 19:06 UTC, brunapereira commented on es6 & beyond/ch8.md
> +Mas JS não é só ES6! Nem perto disso. Já existem algumas novas funcionalidades em vários estágios do desenvolvimento para os temos "além do ES6". Nrsse capítulo, nós brevemente vimos alguns dos mais
boa!

2017-12-11 19:16 UTC, alinedmelo approved these changes

2017-12-11 19:16 UTC, merged