[wip] Scope & Closure: Capítulo 5
cez-aug/You-Dont-Know-JS pull request #167
Opened 2017-12-17 01:39 UTC by gabsprates

Continuando a tradução do **Capítulo 5** do **Scope & Closure**.

Issue de referência: #23

2017-12-20 21:14 UTC, alinedmelo requested changes

2017-12-20 21:14 UTC, alinedmelo commented on scope & closures/ch5.md
> +Os fragmentos de código anteriores são um tanto acadêmicos artificialmente contruídos para ilustrar o *uso de closures*. Mas eu prometi para você uma coisa mais que apenas um novo brinquedinho. Eu pr
```diff
- são um tanto acadêmicos artificialmente contruídos
+ são um tanto acadêmicos e artificialmente construídos
```

2017-12-21 00:04 UTC, gabsprates commented on scope & closures/ch5.md
> +Os fragmentos de código anteriores são um tanto acadêmicos artificialmente contruídos para ilustrar o *uso de closures*. Mas eu prometi para você uma coisa mais que apenas um novo brinquedinho. Eu pr
Legal @alinedmelo!!!

Eu estou aproveitando o tempo livre pra ir mandando essas traduções. Quando eu fechar o subtítulo em questão eu mando um commit com as correções, ok? :wink:

2017-12-21 13:48 UTC, alinedmelo commented on scope & closures/ch5.md
> +Os fragmentos de código anteriores são um tanto acadêmicos artificialmente contruídos para ilustrar o *uso de closures*. Mas eu prometi para você uma coisa mais que apenas um novo brinquedinho. Eu pr
Olá @gabsprates, perfeito! Também vou fazendo no meu tempo livre os reviews, mas pode fazer as correções ao final, o que ficar melhor para você...
Se possível também, existem outros PR que precisam de revisão, se puder.
Obrigada! =D

2018-02-14 18:18 UTC, alinedmelo approved these changes

2018-02-26 21:16 UTC, alinedmelo approved these changes

2018-03-01 02:38 UTC, gabsprates commented
@alinedmelo, @cezaraugusto, @gmsecrieru e @ViltonBonifacio  tudo de boa?

Estou pensando em mandar as correções que forem listadas aqui e já dar o merge no projeto. Daí vou conseguir dar uma atenção para os PR's de revisão e depois foco aqui de novo, mas já vai ficar liberado pra outras pessoas pegarem, se quiserem.

O que acham?

2018-03-22 03:00 UTC, cezaraugusto approved these changes

2018-03-22 15:48 UTC, merged