[FINALIZAÇÃO DE CAPÍTULO (#9)] Types & Grammar CP.1
cez-aug/You-Dont-Know-JS pull request #175
Opened 2018-02-22 19:01 UTC by kelvynrisso

# Antes de enviar seu Pull Request

Faça o check abaixo para ver se o PR está no melhor padrão possível. 
Note que o conteúdo enviado será revisado antes de ser aceito, em geral blocos maiores de tradução levarão mais tempo
para serem aceitos (veja #68). A qualidade do material é um compromisso nosso.

- [ ] Verifique se os jargões estão coerentes com o [WORDREFERENCE](WORDREFERENCE.md)
- [ ] Revise a tradução com carinho :two_hearts: -- seu nome constará na parte que você traduziu.
- [ ] Ao terminar sua parte da tradução, faça um Pull `Request` para o `branch` `portuguese-translation`.
- [ ] Caso o `Pull Request` for o último (finalização de capítulo), use o número da `issue` como referência e faça uso [dessas keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

2018-02-22 19:03 UTC, kelvynrisso commented
Pessoal,
foi a primeira tradução que fiz, então peço que qualquer erro ou detalhe por favor me deem um feedback.

Obrigado.

2018-02-26 21:08 UTC, alinedmelo requested changes

2018-02-26 21:08 UTC, alinedmelo commented on types & grammar/ch1.md
> +**Nota:** Muitos desenvolvedores acreditam que jamais deverá haver variáveis no namespace global, e que tudo deve estar contido em módulos e namespaces privados/separados. Isto é ótimo em teoria, mas
```diff
- Muitos desenvolvedores acreditam que jamais deverá haver variáveis no namespace 
+ Muitos desenvolvedores acreditam que jamais deverá haver qualquer variável no namespace 


```

2018-02-26 21:08 UTC, alinedmelo commented on types & grammar/ch1.md
> +Como um exemplo simples, imagine ter um "modo debug (depuração)" em seu programa que é controlado por uma variável global (flag) chamada `DEBUG`. Você gostaria de verifica se essa variável foi declar
```diff
- Você gostaria de verifica se essa variável foi declarada
+ Você gostaria de verificar se essa variável foi declarada
```

2018-02-26 21:10 UTC, alinedmelo approved these changes

2018-02-26 21:11 UTC, alinedmelo approved these changes

2018-02-26 21:12 UTC, alinedmelo approved these changes

2018-02-26 21:13 UTC, merged