Escopos & Closures: Capítulo 5 [pt-02]
cez-aug/You-Dont-Know-JS pull request #183
Opened 2018-07-10 22:28 UTC by alinedmelo

# Antes de enviar seu Pull Request

Faça o check abaixo para ver se o PR está no melhor padrão possível. 
Note que o conteúdo enviado será revisado antes de ser aceito, em geral blocos maiores de tradução levarão mais tempo
para serem aceitos (veja #68). A qualidade do material é um compromisso nosso.

- [ x] Verifique se os jargões estão coerentes com o [WORDREFERENCE](WORDREFERENCE.md)
- [ x] Revise a tradução com carinho :two_hearts: -- seu nome constará na parte que você traduziu.
- [ x] Ao terminar sua parte da tradução, faça um Pull `Request` para o `branch` `portuguese-translation`.
- [ ] Caso o `Pull Request` for o último (finalização de capítulo), use o número da `issue` como referência e faça uso [dessas keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

2018-07-14 10:24 UTC, gabsprates requested changes
:+1: @alinedmelo good job!

2018-07-14 10:24 UTC, gabsprates commented on scope & closures/ch5.md
> +### Escopo do bloco revisitado
Coloca as primeiras letras com uppercase :wink:

2018-07-14 10:24 UTC, gabsprates commented on scope & closures/ch5.md
> +Olhe atentamente para nossa análise da solução anterior. Nós usamos um IIFE para criar um novo iterador de escopo. Em outras palavras, nós na verdade *precisamos* de um iterador de **bloco de escopo*
```diff
- ... para criar um novo iterador de escopo.
+ ... para criar um novo escopo por iteração.
```

```diff
- ... *precisamos* de um iterador de **bloco de escopo**.
+ ... *precisamos* de um **bloco de escopo** por iteração.
```

Troca **sequestra** por **se apropria de**.

2018-07-14 10:24 UTC, gabsprates commented on scope & closures/ch5.md
> +*Mas isso não é tudo!* (na minha melhor voz de Bob Barker). Há um comportamento especial definido para declarações `let` usadas no topo de um loop for. Esse comportamento diz que a variável vai ser d
Troca **prestativamente** por **proveitosamente**, fica melhor

2018-07-16 20:31 UTC, alinedmelo commented
Vlw @gabsprates, correções feitas! ;D

2018-07-16 20:47 UTC, merged