This & Objetcts Prototypes: Capítulo 2 - Parte 05
cez-aug/You-Dont-Know-JS pull request #196
Opened 2018-07-27 21:31 UTC by alinedmelo

# Antes de enviar seu Pull Request

Faça o check abaixo para ver se o PR está no melhor padrão possível. 
Note que o conteúdo enviado será revisado antes de ser aceito, em geral blocos maiores de tradução levarão mais tempo
para serem aceitos (veja #68). A qualidade do material é um compromisso nosso.

- [x] Verifique se os jargões estão coerentes com o [WORDREFERENCE](WORDREFERENCE.md)
- [x] Revise a tradução com carinho :two_hearts: -- seu nome constará na parte que você traduziu.
- [x] Ao terminar sua parte da tradução, faça um Pull `Request` para o `branch` `portuguese-translation`.
- [ ] Caso o `Pull Request` for o último (finalização de capítulo), use o número da `issue` como referência e faça uso [dessas keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

2018-08-02 01:21 UTC, gabsprates requested changes

2018-08-02 01:21 UTC, gabsprates commented on this & object prototypes/ch2.md
> +Portanto, *binding explícito* tem precedência sobre *binding implícito*, o que significa que você deve perguntar **primeiro** se *o binding explícito* é aplicado antes de verificar pelo *binding impl
Quebra a linha antes desse parágrafo ;)

2018-08-02 01:21 UTC, gabsprates commented on this & object prototypes/ch2.md
> +Se você pensar sobre como o código do helper funciona, não há uma maneira da chamada do operador `new` substituir o hard binding para `obj` como nós observamos.
Quebra de linha antes do parágrafo.

2018-08-02 01:21 UTC, gabsprates commented on this & object prototypes/ch2.md
> +Mas a função nativa `Function.prototype.bind(..)` a partir do ES5 é mais sofisticada, na verdade é mais ou menos. Aqui está o polyfill (ligeriamente reformulado) fornecid pela página do MDN para `bin
"fornecid", faltou uma letra 😜

2018-08-02 01:21 UTC, gabsprates commented on this & object prototypes/ch2.md
> +**Nota** o polyfill de `bind(..)` mostrado acima difere do `bind(..)` nativo no ES5 com respeito à funções com hard binding que serão usadas com `new` (veja abaixo porque isso é útil). Porque o polyf
```diff
- há alguma diferenciação indireta para se aproximar do mesmo comportamento.
+ há uma aproximação suavemente indireta para o mesmo comportamento.
```

2018-08-02 01:21 UTC, gabsprates commented on this & object prototypes/ch2.md
> +Porque a aptidão do `new` de substituir o hard binding é útil?
aptidão -> capacidade

2018-08-02 01:21 UTC, gabsprates commented on this & object prototypes/ch2.md
> +A principal razão para este comportamento é criar uma função (que pode ser usada com `new` para construir objetos) que essencialmente ignora o `this` com *hard binding*, mas que pré configura alguns
Sobrou um espaço depois do "currying".
Essa palavra é um termo que aparece outras vezes aqui e é complicado pra traduzir. Pode colocar no WORDREFERENCE?
Aqui tem uma boa referência: https://en.wikipedia.org/wiki/Currying

2018-08-03 15:22 UTC, alinedmelo commented on this & object prototypes/ch2.md
> +A principal razão para este comportamento é criar uma função (que pode ser usada com `new` para construir objetos) que essencialmente ignora o `this` com *hard binding*, mas que pré configura alguns
Não achei, de fato, uma tradução literal pra esse termo, então atualizei o wordreference com a definição do termo que achei mais sucinta, dê uma olhada, caso precise de alteração ou complemento. 

Vou dar o push das correções acima.

Vlw ;D

2018-08-04 02:50 UTC, merged