This & Objetcts Prototypes: Capítulo 2 - Parte 07
cez-aug/You-Dont-Know-JS pull request #198
Opened 2018-07-27 21:55 UTC by alinedmelo

# Antes de enviar seu Pull Request

Faça o check abaixo para ver se o PR está no melhor padrão possível. 
Note que o conteúdo enviado será revisado antes de ser aceito, em geral blocos maiores de tradução levarão mais tempo
para serem aceitos (veja #68). A qualidade do material é um compromisso nosso.

- [x] Verifique se os jargões estão coerentes com o [WORDREFERENCE](WORDREFERENCE.md)
- [x] Revise a tradução com carinho :two_hearts: -- seu nome constará na parte que você traduziu.
- [x] Ao terminar sua parte da tradução, faça um Pull `Request` para o `branch` `portuguese-translation`.
- [ ] Caso o `Pull Request` for o último (finalização de capítulo), use o número da `issue` como referência e faça uso [dessas keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

2018-08-09 16:22 UTC, gabsprates requested changes
@alinedmelo alguns detalhes :p

2018-08-09 16:22 UTC, gabsprates commented on this & object prototypes/ch2.md
> +Como de costume, há algumas *exceções* nas "regras".
~~nas~~ às "regras"

2018-08-09 16:22 UTC, gabsprates commented on this & object prototypes/ch2.md
> +Se você passar `null` ou` undefined` como um parâmetro de binding do `this` para` call`, `apply` ou` bind`, esses valores serão efetivamente ignorados e, em vez disso, a regra *default binding* será
```diff
- valores serão efetivamente ignorados
+ valores serão de fato ignorados
```

Consertar os espaços:

- ou` undefined`
- para` call`
- ou` bind`

2018-08-09 16:22 UTC, gabsprates commented on this & object prototypes/ch2.md
> +É muito comum usar `apply (..)` para espalhar matrizes de valores como parâmetros para uma chamada de função. Da mesma forma, `bind (..)` pode arranjar parâmetros (valores pré-definidos), o que pode
Em "matrizes de valores", pode deixar "arrays de valores" mesmo.

Consertar os espaços:

- `apply (..)`
- `bind (..)`

2018-08-09 16:22 UTC, gabsprates commented on this & object prototypes/ch2.md
> +Ambas das utilidades requerem um binding `this` para o primeiro parâmetro. Se as funções em questão não se preocuparem com `this`, você precisará de um valor de espaço reservado, e `null` pode parece
```diff
- de um valor de espaço reservado
+ de um valor substituto
```

2018-08-09 16:22 UTC, gabsprates commented on this & object prototypes/ch2.md
> +**Nota:** Não abordamos neste livro, mas o ES6 tem o operador `...` spread que permite sintaticamente "espalhar" um array como parâmetros sem precisar de `apply (..)`, tal como `foo (... [1,2])`, que
Consertar:

- `apply (..)`
- `foo (...[1,2])`
- `foo (1,2)`
- 'this' -> `this`
- curry -> mantém o "currying" aqui
- chamada` bind (..) `ainda

2018-08-09 16:22 UTC, gabsprates commented on this & object prototypes/ch2.md
> +Entretanto, existe um pequeno "perigo" oculto sempre usar `null` quando você não se importa com o binding de `this`. Se você alguma vez usa isso em uma chamada de função (por exemplo, uma função de b
```diff
- oculto sempre usar
+ oculto em sempre usar
```

```diff
- Se você alguma vez usa isso em uma
+ Se você sempre usa isso em uma
```

```diff
- e essa função *não* faz uma referência a this
+ e essa função *faz* uma referência ao `this`
```

E muda *inadvertidamente* por *acidentalmente*, fica melhor ;)

2018-08-09 16:22 UTC, gabsprates commented on this & object prototypes/ch2.md
> +Obviamente, essa armadilha pode levar a uma variedade de bugs *muito difícil* de diagnosticar/rastrear .
difícil -> difíceis

2018-08-16 15:34 UTC, alinedmelo commented
Valeu @gabsprates, correções aplicadas!

2018-08-16 15:47 UTC, merged