This & Objetcts Prototypes: Capítulo 2 - Parte 08
cez-aug/You-Dont-Know-JS pull request #199
Opened 2018-07-30 16:42 UTC by alinedmelo

# Antes de enviar seu Pull Request

Faça o check abaixo para ver se o PR está no melhor padrão possível. 
Note que o conteúdo enviado será revisado antes de ser aceito, em geral blocos maiores de tradução levarão mais tempo
para serem aceitos (veja #68). A qualidade do material é um compromisso nosso.

- [x] Verifique se os jargões estão coerentes com o [WORDREFERENCE](WORDREFERENCE.md)
- [x] Revise a tradução com carinho :two_hearts: -- seu nome constará na parte que você traduziu.
- [x] Ao terminar sua parte da tradução, faça um Pull `Request` para o `branch` `portuguese-translation`.
- [ ] Caso o `Pull Request` for o último (finalização de capítulo), use o número da `issue` como referência e faça uso [dessas keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

2018-08-16 22:53 UTC, gabsprates requested changes

2018-08-16 22:53 UTC, gabsprates commented on this & object prototypes/ch2.md
> +Talvez uma prática mais "segura" seja passar um objeto para `this` que garanta que este não seja um objeto que possa criar efeitos colaterais em seu programa. Pegando emprestado a terminologia da áre
Sobrou um espaço depois do `--`

2018-08-16 22:53 UTC, gabsprates commented on this & object prototypes/ch2.md
> +Já que esse objeto é totalmente vazio, eu pessoalmente gosto de dar um nome de variável `ø` à ele (o símbolo matemático para uma definição vazia). Em muitos teclados (como o US-layout no Mac), esse s
definição -> conjunto

2018-08-16 22:53 UTC, gabsprates commented on this & object prototypes/ch2.md
> +Seja do que for que você o chame, a melhor forma de configurá-lo como **totalmente vazio** é com `Object.create(null)` (veja o Capítulo 5). `Object.create(null)` é similar à `{ }`, mas sem a delegaçã
O último `{}` -> `{ }`

2018-08-16 22:53 UTC, gabsprates commented on this & object prototypes/ch2.md
> +Essa funcionalidade não é apenas "mais segura", há vários benefícios siglísticos para `ø` na medida que se transmite semanticamente "eu quero que o `this` seja vazio" mais claramente do que o `null`
```diff
- benefícios siglísticos para `ø` na medida...
+ benefícios estéticos para `ø`, na medida...
```

2018-08-17 21:56 UTC, alinedmelo commented
Correções aplicadas, vlw! =D

2018-08-17 21:59 UTC, merged