This & Objetcts Prototypes: Capítulo 2 - Parte 10
cez-aug/You-Dont-Know-JS pull request #201
Opened 2018-07-30 19:18 UTC by alinedmelo

# Antes de enviar seu Pull Request

Faça o check abaixo para ver se o PR está no melhor padrão possível. 
Note que o conteúdo enviado será revisado antes de ser aceito, em geral blocos maiores de tradução levarão mais tempo
para serem aceitos (veja #68). A qualidade do material é um compromisso nosso.

- [x] Verifique se os jargões estão coerentes com o [WORDREFERENCE](WORDREFERENCE.md)
- [x] Revise a tradução com carinho :two_hearts: -- seu nome constará na parte que você traduziu.
- [x] Ao terminar sua parte da tradução, faça um Pull `Request` para o `branch` `portuguese-translation`.
- [ ] Caso o `Pull Request` for o último (finalização de capítulo), use o número da `issue` como referência e faça uso [dessas keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

2018-08-19 20:24 UTC, gabsprates requested changes

2018-08-19 20:24 UTC, gabsprates commented on this & object prototypes/ch2.md
> +Nós vimos anteriormente que *hard binding* era uma das estratégias para prevenir que uma chamada de função caia na regra de *default binding* inadivertidamente, forçando-a a ter o binding em um `this
inadivertidamente -> acidentalmente

2018-08-19 20:24 UTC, gabsprates commented on this & object prototypes/ch2.md
> +Seria legal se houvesse uma forma de fornecer um padrão diferente para *default binding* (não `global` ou `undefined`). enquanto continuamos deixando a função capaz de fazer o binding do `this` manua
```diff
- `undefined`). enquanto
+ `undefined`), enquanto
```

2018-08-19 20:24 UTC, gabsprates commented on this & object prototypes/ch2.md
> +A utilidade `softBind(..)` fornecida aqui funciona de forma parecida com a utilidade `bind(..)` nativa do ES5, exceto com nosso comportamento de *soft binding*. Ela encapsula a função especificada na
```diff
- lógica que verifica se o `this` no momento da cahamada é `global` ou `undefined`, usa uma alternativa...
+ lógica que verifica o `this` no momento da chamada e se ele for `global` ou `undefined`, usa uma alternativa...
```

Faltou espaço depois do "`currying` opcional"

2018-08-20 15:04 UTC, alinedmelo commented
Correções feitas! =D

2018-08-20 15:04 UTC, merged