This & Objetcts Prototypes: Capítulo 2 - Parte 11
cez-aug/You-Dont-Know-JS pull request #202
Opened 2018-07-30 20:13 UTC by alinedmelo

# Antes de enviar seu Pull Request

Faça o check abaixo para ver se o PR está no melhor padrão possível. 
Note que o conteúdo enviado será revisado antes de ser aceito, em geral blocos maiores de tradução levarão mais tempo
para serem aceitos (veja #68). A qualidade do material é um compromisso nosso.

- [x] Verifique se os jargões estão coerentes com o [WORDREFERENCE](WORDREFERENCE.md)
- [x] Revise a tradução com carinho :two_hearts: -- seu nome constará na parte que você traduziu.
- [x] Ao terminar sua parte da tradução, faça um Pull `Request` para o `branch` `portuguese-translation`.
- [ ] Caso o `Pull Request` for o último (finalização de capítulo), use o número da `issue` como referência e faça uso [dessas keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

2018-09-16 05:23 UTC, gabsprates requested changes
@alinedmelo, faltou um parágrafo. Me avisa quando mandar pra eu dar uma olhada.

De resto, só esses ajustes mesmo :+1:

2018-09-16 05:23 UTC, gabsprates commented on this & object prototypes/ch2.md
> +Funções normais seguem as 4 regras que acabamos de abordar. Mas o ES6 introduz um tipo especial de função que não usa nenhuma dessas regras: arrow-function.
seguem -> suportam

2018-09-16 05:23 UTC, gabsprates commented on this & object prototypes/ch2.md
> +Arrow functions são identificadas não pela palavra-chave `function`, mas pelo operador `=>` então chamado de "fat arrow". Em vez de usar as quatro regras padrão para o `this`, as arrow functions adot
**Arrow-functions**, deixa o hífen (no restante desse PR também :wink:)

```diff
- binding do `this` do escopo de inclusão
+ binding do `this` para o escopo ao redor
```

2018-09-16 05:23 UTC, gabsprates commented on this & object prototypes/ch2.md
> +A arrow function criada em `foo()` lexicamente captura tudo o que `this` de `foo()` tem em seu tempo de chamada. Já que `foo ()` foi teve binding de `this` para` obj1`, `bar` (uma referência à arrow
```diff
- que `foo ()` foi teve binding de
+ que `foo()` teve binding de
```

2018-09-16 05:23 UTC, gabsprates commented on this & object prototypes/ch2.md
Faltou um parágrafo antes desse snippet

2018-09-16 05:23 UTC, gabsprates commented on this & object prototypes/ch2.md
> +Embora as funções `self = this` e arrow functions pareçam ser boas "soluções" para não querer usar `bind(...)`, elas estão essencialmente fugindo de `this` ao invés de entendê-lo e abraçá-lo.
```diff
- Embora as funções `self = this` e arrow functions
+ Embora `self = this` e arrow-functions
```

2018-09-16 05:23 UTC, gabsprates commented on this & object prototypes/ch2.md
> +2. Adotar os mecanismos de `this` completamente, incluindo o uso de `bind (..)` onde for necessário, e tentar evitar `self = this` e truques  de arrow-functions com "this léxico".
Sobrou espaço em:
- `bind (..)`
- e truques__de arrow-functions

2018-09-18 22:52 UTC, alinedmelo commented
Desculpe a demora, tá bem corrido por aqui rs. 

Correções aplicadas! Deu caca no merge, mas resolvi os conflitos e acho que tá tudo ok mas vale dar uma confirmada antes de mergiar com a portuguese-translation. Vlw =D

2018-09-21 13:00 UTC, merged