Close #32 - This & Objetcts Prototypes: Capítulo 2 - Finalização de Capítulo
cez-aug/You-Dont-Know-JS pull request #203
Opened 2018-07-30 20:26 UTC by alinedmelo

# Antes de enviar seu Pull Request

Faça o check abaixo para ver se o PR está no melhor padrão possível. 
Note que o conteúdo enviado será revisado antes de ser aceito, em geral blocos maiores de tradução levarão mais tempo
para serem aceitos (veja #68). A qualidade do material é um compromisso nosso.

- [x] Verifique se os jargões estão coerentes com o [WORDREFERENCE](WORDREFERENCE.md)
- [x] Revise a tradução com carinho :two_hearts: -- seu nome constará na parte que você traduziu.
- [x] Ao terminar sua parte da tradução, faça um Pull `Request` para o `branch` `portuguese-translation`.
- [ ] Caso o `Pull Request` for o último (finalização de capítulo), use o número da `issue` como referência e faça uso [dessas keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

2018-09-16 05:48 UTC, gabsprates requested changes

2018-09-16 05:48 UTC, gabsprates commented on this & object prototypes/ch2.md
> +Determinar o binding `this` para uma função de execução requer que se encontre o local de chamada direta dessa função. Uma vez examinada, quatro regras podem ser aplicadas ao local de chamada, *nesta
```diff
- para uma função de execução requer que se encontre o local de chamada direta dessa função
+ para uma função em execução requer que se encontre o local de chamada direto dessa função
```

2018-09-16 05:48 UTC, gabsprates commented on this & object prototypes/ch2.md
> +Cuidado com a invocação acidental/involuntária da regra *default binding*. Nos casos em que você deseja "com segurança" ignorar o binding de `this`, um objeto "DMZ" como `ø = Object.create (null)` é
Sobrou espaço em: `ø = Object.create (null)`

2018-09-18 22:50 UTC, alinedmelo commented
Correções feitas!

2018-09-21 13:01 UTC, merged