ES6 & beyond (ES6 e Além) - Capítulo 2 - Parte: let + for
cez-aug/You-Dont-Know-JS pull request #205
Opened 2018-07-30 21:53 UTC by wesmelo

# Antes de enviar seu Pull Request

Faça o check abaixo para ver se o PR está no melhor padrão possível. 
Note que o conteúdo enviado será revisado antes de ser aceito, em geral blocos maiores de tradução levarão mais tempo
para serem aceitos (veja #68). A qualidade do material é um compromisso nosso.

- [X] Verifique se os jargões estão coerentes com o [WORDREFERENCE](WORDREFERENCE.md)
- [X] Revise a tradução com carinho :two_hearts: -- seu nome constará na parte que você traduziu.
- [X] Ao terminar sua parte da tradução, faça um Pull `Request` para o `branch` `portuguese-translation`.
- [ ] Caso o `Pull Request` for o último (finalização de capítulo), use o número da `issue` como referência e faça uso [dessas keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

2018-07-30 22:00 UTC, wesmelo commented
acabei enviando duas partes na mesma pr

2018-08-02 21:38 UTC, alinedmelo requested changes

2018-08-02 21:38 UTC, alinedmelo commented on es6 & beyond/ch2.md
>  What exactly is a constant? It's a variable that's read-only after its initial value is set. Consider:
Faltou remover o parágrafo em inglês aqui: What exactly is a constant...

2018-08-02 21:38 UTC, alinedmelo commented on es6 & beyond/ch2.md
> +Você não tem permissão para alterar o valor que a variável tem uma vez tenha sido definido, no momento da declaração. A declaração da `const` deve ter uma inicialização explícita. Se você quisesse um
```diff
- Você não tem permissão para alterar o valor que a variável tem uma vez tenha sido definido
+ Você não tem permissão para alterar o valor que a variável tem uma vez que tenha sido definido

-  você deveria ter declarado `const a = undefined` tara obtê-la.
+  você deveria ter declarado `const a = undefined` para obtê-la.
```

2018-08-02 21:38 UTC, alinedmelo commented on es6 & beyond/ch2.md
> +Constantes não são a restrição no valor em si, mas na atribuição da variável desse valor. Em outras palavras, o valor não é congelado ou imutável por causa da `const`, apenas a atribuição dele. Se o
```diff
- Constantes não são a restrição no valor em si, mas na atribuição da variável desse valor
+ Constantes não são uma restrição ao valor em si, mas à atribuição da variável desse valor
```

2018-08-02 21:38 UTC, alinedmelo commented on es6 & beyond/ch2.md
> +**Atenção:** Atribuir um objeto ou array como uma constante, significa que o valor não estará disponível para o coletor de lixo até que o escopo léxico dessa constate desapareça pois a referência ao
```diff
- até que o escopo léxico dessa constate desapareça
+ até que o escopo léxico dessa constante desapareça
```

2018-08-02 21:38 UTC, alinedmelo commented on es6 & beyond/ch2.md
> +`const` *pode* ser usada com declarações de variaveis de `for`, `for..in` e `for..of` loops (veja em "for..of Loops"). No entanto, um erro será retornado se houver qualquer tentativa de reatribuição,
```diff
- *pode* ser usada com declarações de variaveis
+ *pode* ser usada com declarações de variáveis
```

2018-08-04 02:22 UTC, wesmelo commented
@alinedmelo ajustado pós revisão

2018-08-04 02:46 UTC, alinedmelo approved these changes

2018-08-04 02:46 UTC, merged