this & Prototipagem de Objetos - cap 4 - Teoria das classes
cez-aug/You-Dont-Know-JS pull request #226
Opened 2018-10-03 21:50 UTC by secato

# Antes de enviar seu Pull Request

Faça o check abaixo para ver se o PR está no melhor padrão possível. 
Note que o conteúdo enviado será revisado antes de ser aceito, em geral blocos maiores de tradução levarão mais tempo para serem aceitos (veja #68). A qualidade do material é um compromisso nosso.

- [X] Verifique se os jargões estão coerentes com o [WORDREFERENCE](WORDREFERENCE.md)
- [X] Revise a tradução com carinho :two_hearts: -- seu nome constará na parte que você traduziu.
- [X] Ao terminar sua parte da tradução, faça um Pull `Request` para o `branch` `portuguese-translation`.
- [ ] Caso o `Pull Request` for o último (finalização de capítulo), use o número da `issue` como referência e faça uso [dessas keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

2018-10-04 16:40 UTC, gmsecrieru requested changes
Muito obrigado <3 Fiz alguns apontamentos/sugestões 😄

2018-10-04 16:40 UTC, gmsecrieru commented on this & object prototypes/ch4.md
> +Continuando com nossa exploração de objetos do capítulo anterior, é natural que agora nós demos atenção a "programação orientada a objetos (OO)", com "classes". Nós primeiro iremos olhar para "orient
```diff
- "orientação de classes"
+ "orientação à classes"
```

```diff
- "(relativo) polimorfismo"
+ "polimorfismo (relativo)"
```

2018-10-04 16:40 UTC, gmsecrieru commented on this & object prototypes/ch4.md
> +Nós veremos que esses conceitos não mapeiam muito naturalmente com o mecanismo de objeto no JS e suas extensões (mixins, etc.). Muitos desenvolvedores JavaScript irão superar esses desafios.
Sugiro "Nós veremos que esses conceitos não mapeiam muito naturalmente para o mecanismo de objetos no JS e também até onde muitos desenvolvedores JavaScript vão para superar estes desafios (mixins etc.)."

2018-10-04 16:40 UTC, gmsecrieru commented on this & object prototypes/ch4.md
> +**Nota:** Este capítulo gasta um bom tempo (a primeira metade!) na pesada teoria de "programação orientada a objeto". Nós finalmente relacionamos essas idéias a um concreto código JavaScript na segun
Acho que o `heavy` se refere mais à extensão do aprofundamento do que à complexidade em si. Sugiro:

```diff
-**Nota:** Este capítulo gasta um bom tempo (a primeira metade!) na pesada teoria de "programação orientada a objeto".
+**Nota:** Este capítulo gasta um tempo considerável (a primeira metada!) na exploração massíva da teoria por trás da "programação orientada a objetos".
```

```diff
- Nós finalmente relacionamos essas idéias a um concreto código JavaScript na segunda metade
+ Nós eventualmente relacionaremos a um código JavaScript concreto na segunda metadade
```

2018-10-04 16:40 UTC, gmsecrieru commented on this & object prototypes/ch4.md
> +OO ou programação orientada a classe enfatiza que os dados têm um comportamento associado intrinsecamente (claro, diferente dependendo do tipo e natureza do dado!) que opera sobre ele, então o design
```diff
- orientada a classe
+ orientada à classes
```

2018-10-04 16:40 UTC, gmsecrieru commented on this & object prototypes/ch4.md
> +Por exemplo, uma série de caracteres que representa uma palavra ou frase geralmente é chamada de "string". Os caracteres são os dados. Mas você quase nunca se importa apenas com os dados, você geralm
```diff
- fazer coisas com o dados
+ fazer coisas com os dados
```

```diff
- anexar dados, busca, etc.)
+ anexar dados, busca etc.)
```

2018-10-04 16:40 UTC, gmsecrieru commented on this & object prototypes/ch4.md
> +Qualquer string é apenas uma instância dessa classe, o que significa que é um pacote bem controlado tanto dos dados de caracteres quanto das funcionalidades que podemos executar nele.
```diff
- é um pacote bem controlado tanto dos dados de caracteres quanto das funcionalidades que podemos executar nele
+ é um pacote cuidadosamente coletado contendo tanto os caracteres quanto as funcionalidades que podemos executar neles.
```

2018-10-04 16:40 UTC, gmsecrieru commented on this & object prototypes/ch4.md
> +Classe também insinuam uma maneira de *classificar* uma certa estrutura de dados, A maneira que nós fazemos isso é pensar em qualquer dada estrutura como uma variação específica de uma definição base
```diff
- uma certa estrutura de dados, A maneira que nós fazemos isso é pensar em qualquer dada estrutura como uma variação específica de uma definição base mais geral
+ uma certa estrutura de dados. A maneira que fazemos isso é assumindo que qualquer estrutura é uma variação específica de uma definição `base` mais ampla.
```

2018-10-04 16:40 UTC, gmsecrieru commented on this & object prototypes/ch4.md
> +Vamos explorar esse processo de classificação olhando para um exemplo comumente citado. Um *carro* pode ser descrito como uma implementação específica de uma "classe" genérica de uma coisa, chamada d
```diff
- Um *carro* pode ser descrito como uma implementação específica de uma "classe" genérica de uma coisa, chamada de *veículo*
+ Um *carro* pode ser descrito como uma implementação específica de uma "classe" de coisas, chamada de *veículo*
```

2018-10-04 16:40 UTC, gmsecrieru commented on this & object prototypes/ch4.md
> +A definição de `Veículo` pode incluir coisas como propulsão (motores, etc.), a capacidade de transportar pessoas, etc., que seriam todos os comportamentos. O que nós definimos em `Veículo` é todo o m
```diff
- motores, etc.
+ motores etc.
```

```diff
- capacidade de transportar pessoas, etc.,
+ capacidade de transportar pessoas etc.,
```

2018-10-04 16:40 UTC, gmsecrieru commented on this & object prototypes/ch4.md
> +repetidas vezes para cada tipo diferente de veículo. Ao invés disso, nós definimos essa capacidade uma vez em `Veículo`, e então quando definimos `Carro`, nós simplesmente indicamos que ele "herda" (
```diff
- "extende"
+ "estende"
```

2018-10-04 16:40 UTC, gmsecrieru commented on this & object prototypes/ch4.md
> +Enquanto `Veículo` e `Carro` definem coletivamente o comportamento por meio de métodos, os dados em uma instância seriam coisas como o "número do chassi" de um carro específico, etc.
```diff
- específico, etc.
+ específico etc.
```

2018-10-04 16:40 UTC, gmsecrieru commented on this & object prototypes/ch4.md
> +A teoria de Classe sugere fortemente que uma classe pai e uma classe filha compartilhem o mesmo nome de método para um determinado comportamento, então esse filho substitui o pai (diferentemente). Co
```diff
- então esse filho
+ de modo que esse filho
```

```diff
- no seu código Javascript
+ no seu código JavaScript
```

2018-10-04 22:33 UTC, secato commented on this & object prototypes/ch4.md
> +Nós veremos que esses conceitos não mapeiam muito naturalmente com o mecanismo de objeto no JS e suas extensões (mixins, etc.). Muitos desenvolvedores JavaScript irão superar esses desafios.
Perfeito, na hora que estava traduzindo acho que uma quebra de linha me "enganou" e eu vi duas orações ao invés de uma.

2018-10-04 23:33 UTC, secato commented on this & object prototypes/ch4.md
> +Qualquer string é apenas uma instância dessa classe, o que significa que é um pacote bem controlado tanto dos dados de caracteres quanto das funcionalidades que podemos executar nele.
Aqui é onde fiquei com mais dúvida. Apesar de collected ser claramente coletado não me parece fazer muito sentido na frase. Olhando em alguns dicionários vi que pode ter o significado de "controlado" apesar de pouco comum.
https://dictionary.cambridge.org/dictionary/english/collected
https://www.linguee.com/english-portuguese/search?source=auto&query=collected

2018-10-05 13:27 UTC, gmsecrieru commented on this & object prototypes/ch4.md
> +Qualquer string é apenas uma instância dessa classe, o que significa que é um pacote bem controlado tanto dos dados de caracteres quanto das funcionalidades que podemos executar nele.
É verdade. Pesquisei "neatly collected" como uma expressão e fiquei com a sensação de que refere-se muito ao cuidado na organização/distribuição:

[#1](https://books.google.com.br/books?id=PrlcCwAAQBAJ&pg=PT1821&lpg=PT1821&dq=neatly+collected&source=bl&ots=wEZKHeZgQ7&sig=quEiIrU1vT6h7M-DQo8c_UbBIuM&hl=pt-BR&sa=X&ved=2ahUKEwjpsPGusu_dAhWLhJAKHUpDB4IQ6AEwD3oECAkQAQ#v=onepage&q=neatly%20collected&f=false)
> (...) Mark Rice was into rock collecting. The bookshelf in his bedroom had two handbooks on rocks, and the rest of the shelves container camples, neatly collected an labeled, some on display, others stored in clear plastic cubes

[#2](https://www.linguee.com.br/ingles-portugues/traducao/neatly+organized.html)
> Now the shop managers can pour all the ready cash into the machine and the various coins are neatly collected in separate trays in record time. 

Faz sentido? O que acha de algo na linha de [cuidadosamente] "arranjado", "distribuído", "organizado"?

2018-10-05 13:30 UTC, gmsecrieru commented on this & object prototypes/ch4.md
> +Qualquer string é apenas uma instância dessa classe, o que significa que é um pacote bem controlado tanto dos dados de caracteres quanto das funcionalidades que podemos executar nele.
Não é exatamente a resposta definitiva mas o [Thesaurus](https://www.thesaurus.com/browse/collected) sugere "disorganized" como um sinônimo possível para "collected". 

Enfim, um palpite apenas! 😄

2018-10-08 14:45 UTC, secato commented on this & object prototypes/ch4.md
> +Qualquer string é apenas uma instância dessa classe, o que significa que é um pacote bem controlado tanto dos dados de caracteres quanto das funcionalidades que podemos executar nele.
Boa, vou de "organizado" então pois me parece soar melhor com o contexto. Valeu pela dica!

2018-10-08 14:58 UTC, secato commented
Gentileza avaliar as correções

2018-10-09 14:39 UTC, gmsecrieru approved these changes

2018-10-09 14:39 UTC, merged

2018-10-09 14:40 UTC, gmsecrieru commented
Ficou ótimo, muito obrigado @secato !