this & object prototype: correções ortográficas
cez-aug/You-Dont-Know-JS pull request #229
Opened 2018-10-09 01:46 UTC by gabsprates

Tava relendo aqui e achei esses errinhos

2018-10-14 20:04 UTC, wesmelo commented
@alinedmelo @cezaraugusto posso revisar?

2018-10-14 20:13 UTC, wesmelo requested changes

2018-10-14 20:13 UTC, wesmelo commented on this & object prototypes/ch2.md
> +**Nota:** Você pode visualizar o call-stack mentalmente ao ver a cadeia de funções em ordem, como fizemos nos comentários no trecho de código anterior. Entretanto, esta é uma forma dolorosa e passíve
[...] Uma outra forma de de ver o call-stack [...]
> Uma outra forma de ver o call-stack

2018-10-16 23:12 UTC, gabsprates commented
♻️ @wesmelo

2018-10-17 16:07 UTC, wesmelo approved these changes

2018-10-19 14:42 UTC, merged