Traduz primeiro parágrafo
cez-aug/You-Dont-Know-JS pull request #249
Opened 2019-01-24 20:03 UTC by mauromattos00

2019-01-25 18:31 UTC, gmsecrieru requested changes

2019-01-25 18:31 UTC, gmsecrieru commented on async & performance/ch2.md
> +No capítulo 1, nós exploramos a terminologia e conceitos acerca da programação assíncrona no JavaScript. Nosso foco foi entender a fila de loop de eventos mono-thread que guia todos os "eventos" (inv
```diff
- invocação de funções assíncronas
+ invocação assíncrona de funções
```

2019-01-25 18:31 UTC, gmsecrieru commented
Obrigado @mauromattos00 ! Fiz apenas uma correção.

2019-01-25 19:38 UTC, mauromattos00 commented on async & performance/ch2.md
> +No capítulo 1, nós exploramos a terminologia e conceitos acerca da programação assíncrona no JavaScript. Nosso foco foi entender a fila de loop de eventos mono-thread que guia todos os "eventos" (inv
Obrigado pela correção @gmsecrieru! É a primeira vez que faço um PR, então não sei como funciona todo o processo exatamente. Eu devo aceitar a sua correção em algum lugar ou fazer um novo PR com a correção realizada?

2019-01-25 19:41 UTC, gmsecrieru commented on async & performance/ch2.md
> +No capítulo 1, nós exploramos a terminologia e conceitos acerca da programação assíncrona no JavaScript. Nosso foco foi entender a fila de loop de eventos mono-thread que guia todos os "eventos" (inv
@mauromattos00 você pode fazer um novo commit com esta alteração sem a necessidade de criar outra PR!

2019-01-27 20:45 UTC, gmsecrieru approved these changes

2019-01-27 20:45 UTC, merged

2019-06-16 03:00 UTC, cezaraugusto commented
@all-contributors please add @mauromattos00 for translation