Tradução capítulo 4: Classes como Design Patterns
cez-aug/You-Dont-Know-JS pull request #253
Opened 2019-03-03 17:21 UTC by AbelCostaJunior

Tradução de parágrafo: Classes como Design Patterns

# Antes de enviar seu Pull Request

Faça o check abaixo para ver se o PR está no melhor padrão possível. 
Note que o conteúdo enviado será revisado antes de ser aceito, em geral blocos maiores de tradução levarão mais tempo
para serem aceitos (veja #68). A qualidade do material é um compromisso nosso.

- [ ] Verifique se os jargões estão coerentes com o [WORDREFERENCE](WORDREFERENCE.md)
- [ ] Revise a tradução com carinho :two_hearts: -- seu nome constará na parte que você traduziu.
- [ ] Certifique-se que a `branch` de sua tradução contém as últimas atualizações da branch `portuguese-translation` do repositório principal.
- [ ] Ao terminar sua parte da tradução, faça um Pull `Request` para o `branch` `portuguese-translation`. 
- [ ] Caso o `Pull Request` for o último (finalização de capítulo), use o número da `issue` como referência e faça uso [dessas keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

2019-03-16 17:44 UTC, gabsprates requested changes
Alguns detalhes.

Toma cuidado pra não deixar as marcações de **bold** e *itálico* pra trás, querendo ou não; elas ajudam a enfatizar termos e fazem diferença no texto.

2019-03-16 17:44 UTC, gabsprates commented on this & object prototypes/ch4.md
> +Talvez você nunca tenha pensado em classes como um "design pattern", já que é muito mais comum ver o debate dos populares "design patterns POO", como o "Iterador", "Observador", "Factory", "Singleton
Acredito que os termos relacionados aos design patters são comuns, não precisa traduzir.
```diff
- como o "Iterador", "Observador", "Factory", "Singleton" e etc.
+ como "Iterator", "Observer", "Factory", "Singleton", etc.
```

- Vírgula depois de "Dessa forma";
- `nível inferior` -> `baixo nível` (termo mais popular na computação/tecnologia);
- `nível superior` -> `alto nível` (mesma coisa aqui; e coloca vírgula antes do parêntese, please :grimacing:);

```diff
- como se ã orientação a objetos fosse na verdade uma base para todo o código.
+ como se a orientação a objetos fosse uma base para *todo* o código (apropriado).
```

2019-03-16 17:44 UTC, gabsprates commented on this & object prototypes/ch4.md
> +Dependendo do seu nível de educação formal em programação, você deve ter ouvido falar de "programação procedural" como uma maneira em que seu código consiste em procedimentos (também conhecidos como
`aprópriada` -> `*apropriada*`

2019-03-16 17:44 UTC, gabsprates commented on this & object prototypes/ch4.md
> +Algumas linguagens (como Java) não te dão o poder de escolha, então não é muito opcional -- tudo é uma classe. Outras linguagens como C/C++ ou PHP fornecem sintaxes procedurais, como orientadas as cl
`muito opcional` -> `muito *opcional*`

```diff
- fornecem sintaxes procedurais, como orientadas as classes, e deixa
+ fornecem sintaxes procedurais e orientadas as classes, e deixam
```

2019-03-17 06:26 UTC, Sw1sh3r commented on this & object prototypes/ch4.md
> +Talvez você nunca tenha pensado em classes como um "design pattern", já que é muito mais comum ver o debate dos populares "design patterns POO", como o "Iterador", "Observador", "Factory", "Singleton
Desculpa amigo, ainda sou um iniciante em github, como eu faço para editar os arquivos de uma pull request?

2019-04-23 23:00 UTC, gabsprates commented on this & object prototypes/ch4.md
> +Talvez você nunca tenha pensado em classes como um "design pattern", já que é muito mais comum ver o debate dos populares "design patterns POO", como o "Iterador", "Observador", "Factory", "Singleton
@dankke, primeiramente, desculpa a demora.
Você pode fazer as edições no arquivo normalmente e criar um novo _commit_, na mesma _branch_. Aí depois é só fazer um _push_ pra essa mesma _branch_ aqui.

2019-06-09 03:17 UTC, cezaraugusto commented
obrigado @s0nicR3ducer  @gabsprates. essa parte foi traduzida por um PR anterior a este e como a traducao ficou parecida, estou fechando esse PR.

2019-06-09 03:17 UTC, closed without merging