Tradução capítulo 4: "Classes" Javascript
cez-aug/You-Dont-Know-JS pull request #254
Opened 2019-03-03 19:06 UTC by AbelCostaJunior

Considerações:

Where does Javascript fall in this regard? => Onde o Javascript cai a esse respeito€ pode ser melhor traduzido, no entanto não consegui encaixar uma tradução melhor que a literal

[...] languages are not like the "classes" you're faking in JS. => A tradução de faking mais coesiva neste caso seria "mentindo", entretanto ainda assim empregada na frase ela ficaria desconexa.

# Antes de enviar seu Pull Request

Faça o check abaixo para ver se o PR está no melhor padrão possível. 
Note que o conteúdo enviado será revisado antes de ser aceito, em geral blocos maiores de tradução levarão mais tempo
para serem aceitos (veja #68). A qualidade do material é um compromisso nosso.

- [ ] Verifique se os jargões estão coerentes com o [WORDREFERENCE](WORDREFERENCE.md)
- [ ] Revise a tradução com carinho :two_hearts: -- seu nome constará na parte que você traduziu.
- [ ] Certifique-se que a `branch` de sua tradução contém as últimas atualizações da branch `portuguese-translation` do repositório principal.
- [ ] Ao terminar sua parte da tradução, faça um Pull `Request` para o `branch` `portuguese-translation`. 
- [ ] Caso o `Pull Request` for o último (finalização de capítulo), use o número da `issue` como referência e faça uso [dessas keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

2019-03-16 18:41 UTC, gabsprates requested changes
Em alguns lugares você deixou `Javascript`, troca pro S (uppercase), please :+1:

2019-03-16 18:41 UTC, gabsprates commented on this & object prototypes/ch4.md
> +Onde o Javascript cai a esse respeito? Js já possuia *alguns* elementos sintáticos baseados em classes (como `new` e `instaceof`) por um tempo, e mais recentemente no ES6, foram feitas algumas adiçõe
```diff
- Onde o Javascript cai a esse respeito? Js já possuia
+ Onde o JavaScript se enquadra nesse aspecto? JS já possuía
```

`instaceof` -> `instanceof` (faltou um N :stuck_out_tongue_closed_eyes:)

2019-03-16 18:41 UTC, gabsprates commented on this & object prototypes/ch4.md
> +Como as classes são um design pattern, você *pode*, com um pouco de esforço (como veremos ao longo desse capítulo), implementar aproximações de muitas funcionalidades clássicas das classes. O JS tent
`desejo` -> `*desejo*`

2019-03-16 18:41 UTC, gabsprates commented on this & object prototypes/ch4.md
> +Embora possamos ter uma sintaxe parecida com as das classes, é como se o mecanismo do Javascript estivesse lutando contra o seu desejo de utilizar o *design pattern de classes*, porque por trás da co
```diff
- Açucar Sintático (e as amplamente utilizadas) bibliotecas "Class"
+ Açúcar sintático e (as amplamente utilizadas) bibliotecas "Class"
```

```diff
- que classes que você tem em outras linguagens não são como as "classes" do Javascript.
+ que as *classes* que você tem em outras linguagens não são como as "classes" que você está simulando em Javascript.
```

2019-06-09 03:22 UTC, cezaraugusto approved these changes
obrigado @s0nicR3ducer @gabsprates. fiz as revisoes. ++!

2019-06-09 03:22 UTC, merged