Tradução capítulo 4: Mecânica das Classes
cez-aug/You-Dont-Know-JS pull request #255
Opened 2019-03-03 22:58 UTC by AbelCostaJunior

# Antes de enviar seu Pull Request

Faça o check abaixo para ver se o PR está no melhor padrão possível. 
Note que o conteúdo enviado será revisado antes de ser aceito, em geral blocos maiores de tradução levarão mais tempo
para serem aceitos (veja #68). A qualidade do material é um compromisso nosso.

- [ ] Verifique se os jargões estão coerentes com o [WORDREFERENCE](WORDREFERENCE.md)
- [ ] Revise a tradução com carinho :two_hearts: -- seu nome constará na parte que você traduziu.
- [ ] Certifique-se que a `branch` de sua tradução contém as últimas atualizações da branch `portuguese-translation` do repositório principal.
- [ ] Ao terminar sua parte da tradução, faça um Pull `Request` para o `branch` `portuguese-translation`. 
- [ ] Caso o `Pull Request` for o último (finalização de capítulo), use o número da `issue` como referência e faça uso [dessas keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

2019-03-17 14:49 UTC, gabsprates requested changes

2019-03-17 14:49 UTC, gabsprates commented on this & object prototypes/ch4.md
> +Na maioria das linguagens orientadas a classes, a "biblioteca padrão" provem uma "stack" de estruturas de dados (push, pop, etc) como uma classe `Stack`.
Um desses:
- as "bibliotecas padrão" proveem
- a "biblioteca padrão" provê

2019-03-17 14:49 UTC, gabsprates commented on this & object prototypes/ch4.md
> +Essa classe teria um conjunto interno de variáveis que armazena dados e um conjunto de comportamentos publicamente acessíveis ("métodos") fornecidos pela classe, o que dá ao seu código a capacidade d
Não quebre a linha aqui, deixa na mesma linha de cima.

```diff
- de interagir com os dados (ocultos), adicionando e removendo outros dados, etc.
+ de interagir (adicionando e removendo, etc.) com os dados (ocultos).
```

2019-03-17 14:49 UTC, gabsprates commented on this & object prototypes/ch4.md
> +Porém em tais linguagens você não precisa trablhar diretamente com essa classe `Stack` (a menos que esteja fazendo uma referência a um membro de uma classe do tipo **Static**, o que está fora do esco
`trablhar` -> `trabalhar` :sweat_smile:

2019-06-09 03:25 UTC, cezaraugusto approved these changes
obrigado @s0nicR3ducer @gabsprates. atualizei com a revisao

2019-06-09 03:26 UTC, merged