Tradução capítulo 4: Construção
cez-aug/You-Dont-Know-JS pull request #256
Opened 2019-03-04 02:29 UTC by AbelCostaJunior

# Antes de enviar seu Pull Request

Faça o check abaixo para ver se o PR está no melhor padrão possível. 
Note que o conteúdo enviado será revisado antes de ser aceito, em geral blocos maiores de tradução levarão mais tempo
para serem aceitos (veja #68). A qualidade do material é um compromisso nosso.

- [ ] Verifique se os jargões estão coerentes com o [WORDREFERENCE](WORDREFERENCE.md)
- [ ] Revise a tradução com carinho :two_hearts: -- seu nome constará na parte que você traduziu.
- [ ] Certifique-se que a `branch` de sua tradução contém as últimas atualizações da branch `portuguese-translation` do repositório principal.
- [ ] Ao terminar sua parte da tradução, faça um Pull `Request` para o `branch` `portuguese-translation`. 
- [ ] Caso o `Pull Request` for o último (finalização de capítulo), use o número da `issue` como referência e faça uso [dessas keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

2019-04-24 04:41 UTC, gabsprates requested changes

2019-04-24 04:41 UTC, gabsprates commented on this & object prototypes/ch4.md
> +Uma arquiteta planeja todos as características de um edifício: quão largo, quão alto, quantas janelas em quais locais, até mesmo o tipo de material que será usado no teto e nas paredes. Até esse pont
```diff
- Uma arquiteta planeja todos as características [...] quantas janelas em quais locais
+ Uma arquiteta planeja todas as características [...] quantas janelas e em quais locais

- ela não necessáriamente se importa, onde o prédio será construido, nem se importa em quantas cópias do edifício serão construídas.
+ ela não necessariamente se importa, *onde* o prédio será construído, nem se importa em *quantas* cópias do edifício serão construídas.
```

2019-04-24 04:41 UTC, gabsprates commented on this & object prototypes/ch4.md
> +Ela também não se importa muito com o conteúdo do edifício - o mobiliário, o papel de parede, ventiladores de teto, etc. - somente o tipo de estrutura que serão contidos.
Mantém os dois tracinhos `--`

2019-04-24 04:41 UTC, gabsprates commented on this & object prototypes/ch4.md
> +Os projetos arquitetônicos que ela produz são apenas planos para um edifício. Eles não constituem realmente um prédio onde podemos caminhar e sentar. Nós precisamos de um construtor para essa determi
- `planos` -> `*planos*`
- Nós precisamos de um construtor para essa ~~determinada~~ tarefa.
- `constrói` -> `*constrói*`
- `copiando` -> `*copiando*`

2019-04-24 04:41 UTC, gabsprates commented on this & object prototypes/ch4.md
> +Uma vez concluído, o prédio é uma instanciação do projeto arquitetônico, espero que um *cópia* perfeita. E então o construtor pode se mover para o lote aberto ao lado e fazer tudo novamente, criando
```diff
- o prédio é uma instanciação do projeto arquitetônico, espero que um *cópia* perfeita.
+ o prédio é uma instanciação física do projeto arquitetônico, com sorte um *cópia* perfeita.
```

2019-04-24 04:41 UTC, gabsprates commented on this & object prototypes/ch4.md
> +O relacionamento entre o prédio e o plano arquitetônico é indireto. Você pode examinar um projeto arquitetônico para entender como o prédio foi estruturado, para todas as partes em que a inspeção dir
```diff
- - a cópia impressa tem apenas linhas desenhadas em uma página represetando onde a porta deveria estar.
+ -- o projeto tem apenas linhas desenhadas em uma página *representando* onde a porta deveria estar.
```

2019-04-24 04:41 UTC, gabsprates commented on this & object prototypes/ch4.md
> +Uma classe é um projeto arquitetônico. Para realmente *conseguir* um objeto com o qual podemos interagir, nós devemos construir (também conhecido como instanciar) algo da classe. O resultado final de
- `instanciar` -> `"instanciar"`

2019-04-24 04:41 UTC, gabsprates commented on this & object prototypes/ch4.md
> +**O objeto é uma cópia** de todas as características descritas pela classe.
`**O objeto é uma cópia**` -> `**O objeto é uma *cópia***`

2019-04-24 04:41 UTC, gabsprates commented on this & object prototypes/ch4.md
> +Como você pode ver, as setas se movem da esquerda para direita, e de cima para baixo, o que indica as operações de cópia que ocorrem tanto conceitualmente quanto físicamente.
`físicamente` -> `fisicamente` (sem acento)

2019-06-13 01:22 UTC, cezaraugusto approved these changes
obrigado @s0nicR3ducer @gabsprates. fiz as correções, aprovando

2019-06-13 01:22 UTC, merged