Tradução capítulo 4: Construtores
cez-aug/You-Dont-Know-JS pull request #257
Opened 2019-03-04 15:51 UTC by AbelCostaJunior

# Antes de enviar seu Pull Request

Faça o check abaixo para ver se o PR está no melhor padrão possível. 
Note que o conteúdo enviado será revisado antes de ser aceito, em geral blocos maiores de tradução levarão mais tempo
para serem aceitos (veja #68). A qualidade do material é um compromisso nosso.

- [ ] Verifique se os jargões estão coerentes com o [WORDREFERENCE](WORDREFERENCE.md)
- [ ] Revise a tradução com carinho :two_hearts: -- seu nome constará na parte que você traduziu.
- [ ] Certifique-se que a `branch` de sua tradução contém as últimas atualizações da branch `portuguese-translation` do repositório principal.
- [ ] Ao terminar sua parte da tradução, faça um Pull `Request` para o `branch` `portuguese-translation`. 
- [ ] Caso o `Pull Request` for o último (finalização de capítulo), use o número da `issue` como referência e faça uso [dessas keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

2019-04-25 04:18 UTC, gabsprates requested changes

2019-04-25 04:18 UTC, gabsprates commented on this & object prototypes/ch4.md
> +Instâncias das classes são construídas por um método especial da classe, que geralmente possui o mesmo nome da classe, chamado de construtor. O trabalho desse método é inicializar qualquer informação
`construtor` -> `*construtor*`

2019-04-25 04:18 UTC, gabsprates commented on this & object prototypes/ch4.md
> +Para *fazer* uma instância de `CoolGuy`, nós vamos chamar o construtor da classe:
Acho que *criar* encaixa melhor que *fazer*, nesse contexto. Que tal?

2019-04-25 04:18 UTC, gabsprates commented on this & object prototypes/ch4.md
> +Perceba que a classe `CoolGuy` tem um construtor `CoolGuy()`, que é o que chamamos quando dizemos `ǹew CoolGuy(..)`. Nós temos como retorno um objeto (uma instância da nossa classe) do construtor, e
`ǹew` -> `new` (sem o acento no N)

2019-04-25 04:18 UTC, gabsprates commented on this & object prototypes/ch4.md
> +O construtor de uma classe pertence a classe, quase universalmente com o mesmo nome da classe. Além disso, construtores quase sempre precisam ser chamados com o operador `new` para que o motor da lin
`pertence` -> `*pertence*`

2019-06-15 15:27 UTC, cezaraugusto approved these changes
obrigado @s0nicR3ducer @gabsprates. fiz as alterações, aprovando.

2019-06-15 15:27 UTC, merged