..
cez-aug/You-Dont-Know-JS pull request #328
Opened 2020-01-28 17:57 UTC by Nerd0000

Pull request em virtude de uma melhora no readme

2020-04-07 15:29 UTC, gabsprates requested changes

2020-04-07 15:29 UTC, gabsprates commented on README.md
> -* Leia online (grátis!): ["Iniciando"](up\%20&\%20going/README.md#you-dont-know-js-iniciando), Publicado: [Compre agora (inglês)](http://shop.oreilly.com/product/0636920039303.do), ebook format is gr
No arquivo original ([em inglês](https://github.com/getify/You-Dont-Know-JS/tree/1st-ed#titles)) consta a expressão:
> but the ebook format is free!

Corrige essa tradução, por favor, mantendo a frase.

2020-04-21 18:47 UTC, gabsprates reviewed
@Nerd0000, pode fazer um squash dos dois commits, por favor?

2020-04-23 18:38 UTC, Nerd0000 commented
O quê seria isso?

2020-04-24 12:38 UTC, gmsecrieru commented
Fazemos squash no merge mesmo, valeu @Nerd0000 !

2020-04-24 12:38 UTC, merged