Async & Performance Cap. 2 - restante da introdução
cez-aug/You-Dont-Know-JS pull request #331
Opened 2020-04-23 18:47 UTC by nielvag

# Antes de enviar seu Pull Request

Faça o check abaixo para ver se o PR está no melhor padrão possível. 
Note que o conteúdo enviado será revisado antes de ser aceito, em geral blocos maiores de tradução levarão mais tempo
para serem aceitos (veja #68). A qualidade do material é um compromisso nosso.

- [x] Verifique se os jargões estão coerentes com o [WORDREFERENCE](WORDREFERENCE.md)
- [x] Revise a tradução com carinho :two_hearts: -- seu nome constará na parte que você traduziu.
- [x] Certifique-se que a `branch` de sua tradução contém as últimas atualizações da branch `portuguese-translation` do repositório principal.
- [x] Ao terminar sua parte da tradução, faça um Pull `Request` para o `branch` `portuguese-translation`. 
- [x] Caso o `Pull Request` for o último (finalização de capítulo), use o número da `issue` como referência e faça uso [dessas keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

2020-05-21 01:37 UTC, gabsprates requested changes

2020-05-21 01:37 UTC, gabsprates commented on async & performance/ch2.md
> +`// A` e `// B` representam a primeira metade do programa (também conhecido como *agora*) e `// C` marca a segunda metade (também conhecido como *depois*). A primeira metade é executada imediatamente
```suggestion
`// A` e `// B` representam a primeira metade do programa (também conhecido como *agora*) e `// C` marca a segunda metade (também conhecida como *depois*). A primeira metade é executada imediatamente e, em seguida, há uma "pausa" de duração indeterminada. Em algum momento futuro, se a chamada Ajax for concluída, a execução do programa partirá de onde parou e *continuará* com a segunda metade.
```

2020-05-21 01:37 UTC, gabsprates commented on async & performance/ch2.md
> +Em outras palavras, a função de callback (retorno) envolve ou encapsula a *continuação* do programa.
Sobre a expressão `(retorno)`, já existe o termo callback mais acima, não sei se precisa. O que acha?

2020-05-21 01:37 UTC, gabsprates commented on async & performance/ch2.md
> +Assim que introduzimos uma só dessas continuações (ou várias dezenas de programas!) na forma de calllback, permitimos formar uma divergência entre o funcionamento de nossos cérebros e a maneira como
```suggestion
Assim que introduzimos uma só dessas continuações (ou várias dezenas como muitos programas fazem!) na forma de uma callback, permitimos formar uma divergência entre o funcionamento de nossos cérebros e a maneira como o código funcionará. Sempre que esses dois divergem (e longe desse ser o único lugar que isso acontece, como eu tenho certeza que você sabe!), nos deparamos com o fato inevitável de que nosso código se torna mais difícil de entender, raciocinar, depurar e manter.
```

2020-05-22 01:04 UTC, nielvag commented on async & performance/ch2.md
> +Em outras palavras, a função de callback (retorno) envolve ou encapsula a *continuação* do programa.
De acordo! Obrigado pelo feedback.
Não tenho muita prática com git e github ainda, mas espero que possa ajudar mais do que atrapalhar. rsrs

2020-05-22 01:17 UTC, nielvag commented
Fiz um commit com as correções. Não tenho certeza se é só isso ou se é de outra forma...

2020-05-30 20:40 UTC, gabsprates requested changes

2020-05-30 20:40 UTC, gabsprates commented on async & performance/ch2.md
> +`// A` e `// B` representam a primeira metade do programa (também conhecido como *agora*) e `// C` marca a segunda metade (também conhecida como *depois*). A primeira metade é executada imediatamente
```suggestion
`// A` e `// B` representam a primeira metade do programa (também conhecido como *agora*) e `// C` marca a segunda metade (também conhecida como *depois*). A primeira metade é executada imediatamente e, em seguida, há uma "pausa" de duração indeterminada. Em algum momento futuro, se a chamada Ajax for concluída, a execução do programa partirá de onde parou e *continuará* com a segunda metade.
```

2020-05-30 20:40 UTC, gabsprates commented on async & performance/ch2.md
> +Assim que introduzimos uma só dessas continuações (ou várias dezenas como muitos programas fazem!) na forma de calllback, permitimos formar uma divergência entre o funcionamento de nossos cérebros e
```suggestion
Assim que introduzimos uma só dessas continuações (ou várias dezenas como muitos programas fazem!) na forma de uma callback, permitimos formar uma divergência entre o funcionamento de nossos cérebros e a maneira como o código funcionará. Sempre que esses dois divergem (e longe desse ser o único lugar que isso acontece, como eu tenho certeza que você sabe!), nos deparamos com o fato inevitável de que nosso código se torna mais difícil de entender, raciocinar, depurar e manter.
```

2020-06-08 23:31 UTC, gabsprates requested changes
@nielvag, obrigado pelas correções e traduções. 👏 

Só faz um favor: junta os commits de correções no commit da respectiva seção, pra árvore de commits ficar o mais enxuta possível. Beleza?

2020-06-08 23:31 UTC, gabsprates commented on async & performance/ch2.md
> +Tenho certeza de que a maioria de vocês, leitores, já ouviu alguém dizer (até fez a afirmação): "Sou multitarefa". Os efeitos de tentar agir como uma multitarefa variam de humor (por exemplo, do jogo
```suggestion
Tenho certeza de que a maioria de vocês, leitores, já ouviram alguém dizer (até mesmo fez a afirmação): "Sou multitarefa". Os efeitos de tentar agir como uma multitarefa variam de humor (por exemplo, do jogo bobo das crianças batendo na cabeça e esfregando o estômago) ao mundano (mascar chiclete enquanto caminha) até completamente perigoso (mensagens de texto enquanto dirige).
```

2020-06-08 23:31 UTC, gabsprates commented on async & performance/ch2.md
> +Assim que introduzimos uma só dessas continuações (ou várias dezenas como muitos programas fazem!) na forma de uma calllback, permitimos formar uma divergência entre o funcionamento de nossos cérebro
```suggestion
Assim que introduzimos uma só dessas continuações (ou várias dezenas como muitos programas fazem!) na forma de uma callback, permitimos formar uma divergência entre o funcionamento de nossos cérebros e a maneira como o código funcionará. Sempre que esses dois divergem (e longe desse ser o único lugar que isso acontece, como eu tenho certeza que você sabe!), nos deparamos com o fato inevitável de que nosso código se torna mais difícil de entender, raciocinar, depurar e manter.
```

Você notou a palavra _calllback_ escrita com 3 L? 😅

2020-06-08 23:31 UTC, gabsprates commented on async & performance/ch2.md
> +`// A` e `// B` representam a primeira metade do programa (também conhecido como *agora*) e `// C` marca a segunda metade (também conhecida como *depois*). A primeira metade é executada imediatamente
Lembra de tirar o "_do_" aqui 😉

2020-06-09 21:49 UTC, nielvag commented on async & performance/ch2.md
> +Assim que introduzimos uma só dessas continuações (ou várias dezenas como muitos programas fazem!) na forma de uma calllback, permitimos formar uma divergência entre o funcionamento de nossos cérebro
haha não mesmo. Eu li dezenas de vezes e não vi. Vlw!

2020-06-09 21:53 UTC, nielvag commented on async & performance/ch2.md
> +`// A` e `// B` representam a primeira metade do programa (também conhecido como *agora*) e `// C` marca a segunda metade (também conhecida como *depois*). A primeira metade é executada imediatamente
Obrigado pela paciência cara, kkk. Vou me atentar melhor aos detalhes.

2020-06-09 22:30 UTC, nielvag commented
> @nielvag, obrigado pelas correções e traduções. clap
> 
> Só faz um favor: junta os commits de correções no commit da respectiva seção, pra árvore de commits ficar o mais enxuta possível. Beleza?

Pronto. Fiz certo?

2020-06-09 23:05 UTC, gabsprates commented
@nielvag, na verdade, não... 😬
Acabou criando mais 3 commits... Eu posso juntar tudo em um só e fazer o merge, mas não é legal porque não fica com todas as referências das coisas que você fez.

Recomendo você juntar todos os commits em 1 e depois separá-los por seções.
Essa talk explica bem como fazer isso:
https://www.youtube.com/watch?v=dix7u-LYE-A

2020-06-10 22:26 UTC, nielvag commented
> @nielvag, na verdade, não... grimacing
> Acabou criando mais 3 commits... Eu posso juntar tudo em um só e fazer o merge, mas não é legal porque não fica com todas as referências das coisas que você fez.
> 
> Recomendo você juntar todos os commits em 1 e depois separá-los por seções.
> Essa talk explica bem como fazer isso:
> https://www.youtube.com/watch?v=dix7u-LYE-A


Que confusão eu fiz, rsrs.

Obrigado pela paciência cara. Tenho aprendido bastante coisa.

Será que ficou bom agora? Juntei todos com `git rebase -i` e separei as seções usando `git add -p`.

2020-06-11 00:21 UTC, gabsprates approved these changes
Ficou excelente, @nielvag!
Parabéns e obrigado! 👏

2020-06-11 00:24 UTC, merged