Tradução de Async & Performace - Cap. 2 - seção: Sequential Brain
cez-aug/You-Dont-Know-JS pull request #335
Opened 2020-06-11 23:24 UTC by nielvag

# Antes de enviar seu Pull Request

Faça o check abaixo para ver se o PR está no melhor padrão possível. 
Note que o conteúdo enviado será revisado antes de ser aceito, em geral blocos maiores de tradução levarão mais tempo
para serem aceitos (veja #68). A qualidade do material é um compromisso nosso.

- [x] Verifique se os jargões estão coerentes com o [WORDREFERENCE](WORDREFERENCE.md)
- [x] Revise a tradução com carinho :two_hearts: -- seu nome constará na parte que você traduziu.
- [x] Certifique-se que a `branch` de sua tradução contém as últimas atualizações da branch `portuguese-translation` do repositório principal.
- [x] Ao terminar sua parte da tradução, faça um Pull `Request` para o `branch` `portuguese-translation`. 
- [x] Caso o `Pull Request` for o último (finalização de capítulo), use o número da `issue` como referência e faça uso [dessas keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

2020-06-11 23:28 UTC, nielvag commented on async & performance/ch2.md
> -Does that sound suspiciously like async evented concurrency (like the sort that happens in JS) to you?! If not, go back and read Chapter 1 again!
Eu fiquei com dúvida nessa parte. Pra mim parece fazer sentido, mas confesso que não entendi muito bem o termo _async evented concurrency_. Seria o caso de criar uma issue?

2020-06-20 03:12 UTC, gabsprates commented
Oi @nielvag, te pedir um favor relacionado a esse PR:

**Deixa o commit `81a7f75c3f7a1daa1102443c62903784b8e40aac` de fora desse PR, _please_?**
É uma seção grande, se for terminar ela e deixar nesse mesmo PR vai ficar um bem pesado pra revisar.

Recomendo deixar os outros dois commits e, dependendo do andamento da tradução da seção "Callbacks Aninhados/Encadeados", abrir um outro PR com a tradução dela.

Pretendo começar a revisar o mais rápido possível.

2020-06-20 16:02 UTC, nielvag commented
> `81a7f75c3f7a1daa1102443c62903784b8e40aac`

Prontinho!

Na verdade a intenção era essa mesmo, um PR por seção, :sweat_smile:. Obrigado!

2020-06-20 18:09 UTC, gabsprates commented
Ótimo! Obrigado (:

Faz um rebase dessa branch? O primeiro parágrafo desse PR já está traduzido na branch principal.

2020-06-20 19:32 UTC, nielvag commented
> Ótimo! Obrigado (:
> 
> Faz um rebase dessa branch? O primeiro parágrafo desse PR já está traduzido na branch principal.

Dessa forma?

2020-06-22 23:24 UTC, gabsprates commented
Não, não. Era pra ter só o teu commit e tua árvore ficaria assim:

```
teu_commit
|
048241c16288d0723080c9a3566b6207a639753e (cezaraugusto/portuguese-translation)
|
471058f0b90d533b9f1ec7a7ef28b10960ad953c
|
b424e222fd113a4a8e282c35c931f23d10e270d8
|
...
```

Talvez apontar tua branch pra `cezaraugusto/portuguese-translation` e depois usar o `git cherry-pick` pra pegar teu commit seja melhor nesse caso, já que tua branch também chama `portuguese-translation`

2020-06-29 23:26 UTC, nielvag commented
Oi @gabsprates, perdão pela demora.
Minha árvore ficou como você descreveu acima, porém com os dois _commits_ de tradução da seção _Sequencial Brain_, um com a tradução do primeiro parágrafo e outro com o restante. Então, fiz o rebase pra junta-los, só que a referência (cezaraugusto/portuguese-translation) não aparece mais. Tem algum problema ou é dessa forma?

2020-07-01 21:05 UTC, gabsprates commented
Oi, @nielvag.

Tem problema sim :eyes:
Nesse caso, se fizer o merge assim, teremos commits duplicados e isso não é legal. Uma coisas que você pode fazer é:
0. atualizar o remote (ex.: `git fetch cezaraugusto portuguese-translation`);
1. salvar o hash do commit da tradução da seção desse PR;
2. apontar tua branch pra `cezaraugusto/portuguese-translation` (`git reset --hard cezaraugusto/portuguese-translation`)
3. fazer um `git cherry-pick` do hash do commit salvo no passo `1`

Fazendo isso é provável que dê conflito (durante o `cherry-pick`) por causa do primeiro parágrafo da seção _Sequential Brain_, mas aí é só resolver e seguir os passos que o `cherry-pick` sugere.

Se não der conflito, sucesso hehe

2020-07-02 14:47 UTC, nielvag commented
Só consegui atualizar o remote com o `git pull cezaraugusto portuguese-translation`. Depois segui os passos, mas não deu conflito no `cherry-pick`, então ficou dois commits com a tradução da "Sequential Brain".

Na verdade, foi o mesmo passo a passo que fiz anteriormente, só que antes eu dava um `rebase` pra juntar os dois commits e perdia a referência do repositório remoto.

O que faço agora?

2020-07-02 16:38 UTC, gabsprates commented
Agora tá certinho!
![image](https://user-images.githubusercontent.com/12635603/86387258-4dbc5e80-bc69-11ea-8729-8d82f00afaf8.png)

Vou fazer a revisão da tradução e te dou feedback 😉

2020-07-07 01:18 UTC, gabsprates requested changes

2020-07-07 01:18 UTC, gabsprates commented on async & performance/ch2.md
> +Não estou falando de todas as nossas funções cerebrais involuntárias, subconscientes e automáticas, como batimentos cardíacos, respiração e pálpebras piscando. Todas essas são tarefas vitais para a n
```suggestion
Não estou falando de todas as nossas funções cerebrais involuntárias, subconscientes e automáticas, como batimentos cardíacos, respiração e pálpebras piscando. Todas essas são tarefas vitais para a nossa vida sustentável, mas não alocamos intencionalmente qualquer poder cerebral a elas. Felizmente, enquanto estamos obcecados em verificar feeds de redes sociais pela 15ª vez em três minutos, nosso cérebro continua em segundo plano (threads!) com todas essas tarefas importantes.
```
Parece que o _while_ nessa última frase encaixa melhor com a ideia de paralelismo. O que acha?

2020-07-07 01:18 UTC, gabsprates commented on async & performance/ch2.md
> +Em vez disso, estamos falando sobre qualquer tarefa que esteja na vanguarda de nossas mentes no momento. Para mim, é estar escrevendo o texto neste livro agora. Estou executando alguma outra função c
```suggestion
Em vez disso, estamos falando sobre qualquer tarefa que esteja na linha de frente das nossas mentes no momento. Para mim, é estar escrevendo o texto neste livro agora. Estou executando alguma outra função cerebral de nível superior exatamente neste mesmo momento? Não, na verdade não. Eu me distraio com rapidez e facilidade -- algumas dezenas de vezes nesses últimos parágrafos!
```
Atenção ao `-`

2020-07-07 01:18 UTC, gabsprates commented on async & performance/ch2.md
> +Quando *fingimos* multitarefa, como tentar digitar algo ao mesmo tempo em que conversamos com um amigo ou membro da família por telefone, o que realmente estamos fazendo é agir como alternadores de c
```suggestion
Quando *fingimos* multitarefa, como tentar digitar algo ao mesmo tempo em que conversamos com um amigo ou membro da família por telefone, o que realmente estamos fazendo é agir como rápidos alternadores de contexto. Em outras palavras, alternamos entre duas ou mais tarefas em rápida sucessão, progredindo *simultaneamente* em cada tarefa em pedaços pequenos e rápidos. Fazemos isso tão velozmente que, para o mundo exterior, parece que estamos realizando essas coisas *em paralelo*.
```

2020-07-07 01:18 UTC, gabsprates commented on async & performance/ch2.md
> -Does that sound suspiciously like async evented concurrency (like the sort that happens in JS) to you?! If not, go back and read Chapter 1 again!
Acho que não. Me parece que o autor se refira à [Programação Concorrente](https://pt.wikipedia.org/wiki/Programa%C3%A7%C3%A3o_concorrente) mesmo, principalmente pelo contexto desse livro.

2020-07-07 01:18 UTC, gabsprates commented on async & performance/ch2.md
> +Isso parece suspeito como concorrência de evento assíncrono (tipo como acontece em JS) para você?! Se não, volte e leia o Capítulo 1 novamente!
```suggestion
Isso parece como concorrência assíncrona de eventos (semelhante ao que acontece em JS) para você?! Se não, volte e leia o Capítulo 1 novamente!
```

2020-07-07 01:18 UTC, gabsprates commented on async & performance/ch2.md
> +Na verdade, uma maneira de simplificar (ou seja, abusar) o mundo massivamente complexo da neurologia em algo que eu posso remotamente esperar discutir aqui é que nosso cérebro funciona como a fila de
```suggestion
Na verdade, uma maneira de simplificar (ou seja, abusar) o mundo massivamente complexo da neurologia em algo que eu possa remotamente esperar discutir aqui é que nosso cérebro funciona como a fila de loop de eventos.
```

2020-07-07 01:18 UTC, gabsprates commented on async & performance/ch2.md
> +Eu não sou interrompido e puxado para outro "processo" em todas as oportunidades que eu poderia ter (felizmente - ou esse livro nunca seria escrito!). Mas isso acontece frenquente o suficiente para q
```suggestion
Eu não sou interrompido e puxado para outro "processo" em todas as oportunidades que eu poderia ter (felizmente -- ou esse livro nunca seria escrito!). Mas isso acontece frequente o suficiente para que eu sinta que meu próprio cérebro está quase constantemente mudando para vários contextos diferentes (também conhecidos como "processos"). E é muito parecido com o que o mecanismo JS provavelmente sentiria.
```

2020-07-07 13:56 UTC, nielvag commented
Oi @gabsprates, fantástica sua revisão, obrigado!

Queria poder revisar sua PR tb, mas acredito que agregaria pouco. Se houver alguma outra coisa que possa contribuir, estou por aqui. :wink:

2020-07-08 00:32 UTC, gabsprates commented
@nielvag, dá uma olhada lá (na PR), se ver alguma coisa, é só comentar hehe (:

Só ajusta os commits aqui, por favor. Tenta deixar em um só, pra a gente manter a árvore de commits o mais limpa possível.

2020-07-08 16:34 UTC, nielvag commented
@gabsprates , tá ok?

Como faremos pra juntar os commits relacionados a esta seção?

2020-07-08 22:14 UTC, gabsprates approved these changes

2020-07-08 22:14 UTC, gabsprates commented
> 
> 
> @gabsprates , tá ok?
> 
> Como faremos pra juntar os commits relacionados a esta seção?

Quais commits?

2020-07-08 22:15 UTC, merged

2020-07-08 23:40 UTC, nielvag commented
> > @gabsprates , tá ok?
> > Como faremos pra juntar os commits relacionados a esta seção?
> 
> Quais commits?

Esses: _471058f0b90d533b9f1ec7a7ef28b10960ad953c_ e _5a7c56563c370a345585a91661a59b6af2837e66_.

2020-07-09 00:07 UTC, gabsprates commented
O _merge_ cuidou disso sozinho, não precisa preocupar que já tá tudo na _branch_ principal 😉