Tradução de Async & Performace - Cap. 2 - seção: Doing Versus Planning
cez-aug/You-Dont-Know-JS pull request #339
Opened 2020-06-20 15:54 UTC by nielvag

# Antes de enviar seu Pull Request

Faça o check abaixo para ver se o PR está no melhor padrão possível. 
Note que o conteúdo enviado será revisado antes de ser aceito, em geral blocos maiores de tradução levarão mais tempo
para serem aceitos (veja #68). A qualidade do material é um compromisso nosso.

- [x] Verifique se os jargões estão coerentes com o [WORDREFERENCE](WORDREFERENCE.md)
- [x] Revise a tradução com carinho :two_hearts: -- seu nome constará na parte que você traduziu.
- [x] Certifique-se que a `branch` de sua tradução contém as últimas atualizações da branch `portuguese-translation` do repositório principal.
- [x] Ao terminar sua parte da tradução, faça um Pull `Request` para o `branch` `portuguese-translation`. 
- [x] Caso o `Pull Request` for o último (finalização de capítulo), use o número da `issue` como referência e faça uso [dessas keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

2020-07-08 22:28 UTC, gabsprates commented
@nielvag, acredito que, como essa branch tem um nome diferente de `portuguese-translation`, não teremos os problemas que tivemos no #335. Pode fazer o _rebase_?

2020-07-08 23:34 UTC, nielvag commented
@gabsprates, dessa forma?

2020-08-13 01:28 UTC, gabsprates requested changes
Demorei bastante pra me organizar e terminar esse, perdão.
Consegui! 😅

2020-08-13 01:28 UTC, gabsprates commented on async & performance/ch2.md
> +Novamente, voltando à redação deste texto como minha metáfora. Meu plano básico de esboço mental aqui é continuar escrevendo e escrevendo, passando sequencialmente por um conjunto de pontos que orden
O que acha dessas alterações?
```suggestion
Novamente, voltando à redação deste texto como minha metáfora. O esboço grosseiro do meu plano aqui é continuar escrevendo e escrevendo, passando sequencialmente por um conjunto de pontos que ordenei em meus pensamentos. Não pretendo ter nenhuma interrupção ou atividade não linear neste trabalho. Mas mesmo assim, meu cérebro está fazendo rodízio o tempo todo.
```

2020-08-13 01:28 UTC, gabsprates commented on async & performance/ch2.md
> +Você notará que esse pensamento de nível superior (planejamento) não parece muito assíncrono em sua formulação. De fato, é meio raro pensarmos deliberadamente apenas em termos de eventos. Em vez diss
```suggestion
Você notará que esse pensamento (planejamento) de alto nível não parece muito com eventos assíncronos em sua formulação. De fato, é meio raro pensarmos deliberadamente apenas em termos de eventos. Em vez disso, planejamos as coisas com cuidado, sequencialmente (A então B e depois C), e assumimos, de certa forma, uma espécie de bloqueio temporal que força B a esperar A e C a esperar B.
```

2020-08-13 01:28 UTC, gabsprates commented on async & performance/ch2.md
> +Quando um desenvolvedor escreve código, ele está planejando um conjunto de ações para ocorrer. Se eles são bons em ser desenvolvedor, estão **planejando cuidadosamente.** "Eu preciso definir `z` para
A frase em inglês tá meio sem concordância de número. O que acha de deixarmos padronizado pra usar plural?
```suggestion
Quando desenvolvedores escrevem código, eles estão planejando a execução de um conjunto de ações. Se eles são bons em ser desenvolvedores, estão **planejando cuidadosamente**. "Eu preciso definir `z` para o valor de `x` e depois `x` para o valor de `y`," e assim por diante.
```

2020-08-13 01:28 UTC, gabsprates commented on async & performance/ch2.md
> +Essas três instruções de atribuição são síncronas, portanto, `x = y` espera que `z = x` termine, e `y = z`, por sua vez, espera que `x = y` termine. Outra maneira de dizer é que essas três instruções
```suggestion
Essas três instruções de atribuição são síncronas, portanto `x = y` espera que `z = x` termine e `y = z`, por sua vez, espera que `x = y` termine. Outra maneira de dizer é que essas três instruções são temporariamente obrigadas a executar em uma determinada ordem, uma logo após a outra. Felizmente, não precisamos nos preocupar com detalhes de eventos assíncronos aqui. Se o fizermos, o código fica muito mais complexo, rapidamente!
```

2020-08-13 01:28 UTC, gabsprates commented on async & performance/ch2.md
> +Acontece que a maneira como expressamos assincronia (com retornos de chamada) em nosso código não é muito boa para esse comportamento de planejamento do cérebro síncrono.
```suggestion
Acontece que a maneira como expressamos assincronia (com callbacks) em nosso código não é muito boa para essa maneira de planejar do cérebro síncrono.
```

2020-08-13 01:28 UTC, gabsprates commented on async & performance/ch2.md
> +> "Eu preciso ir à loja, mas no caminho tenho certeza de que vou receber um telefonema, então 'Oi, mãe', e enquanto ela começa a falar, procurarei o endereço da loja no GPS, mas isso levará um segund
`diff` no trecho do cinto de segurança:
```suggestion
> "Eu preciso ir à loja, mas no caminho tenho certeza de que vou receber um telefonema, então 'Oi, mãe', e enquanto ela começa a falar, procurarei o endereço da loja no GPS, mas isso levará um segundo para carregar, então eu vou desligar o rádio para ouvir melhor mamãe, depois vou perceber que esqueci de vestir uma jaqueta e está frio lá fora, mas não importa, continuo dirigindo e conversando com mamãe e, em seguida, o toque do cinto de segurança me lembra de colocá-lo, então 'Sim, mãe, estou usando meu cinto de segurança, sempre uso!'. Ah, finalmente o GPS recebeu as instruções, agora..."
```

2020-08-13 01:28 UTC, gabsprates commented on async & performance/ch2.md
> +A razão pela qual é difícil para nós, como desenvolvedores, escrever código assíncrono, especialmente quando tudo o que temos é o retorno de chamadas (callback), é que o fluxo de pensamento/planejame
```suggestion
A razão pela qual é difícil para nós, como desenvolvedores, escrever código assíncrono, especialmente quando tudo o que temos são callback, é que o fluxo de pensamento/planejamento consciente não é natural para a maioria de nós.
```

2020-08-13 01:28 UTC, gabsprates commented on async & performance/ch2.md
> +Nós pensamos em termos sequenciais, mas as ferramentas (retornos de chamada) disponíveis no código não são expressas de uma maneira gradual (passo a passo) uma vez que passamos de síncrono para assín
```suggestion
Nós pensamos em termos sequenciais, mas as ferramentas disponíveis no código (callbacks) não são expressas de uma maneira sequencial uma vez que passamos de síncrono para assíncrono.
```

2020-08-13 01:28 UTC, gabsprates commented on async & performance/ch2.md
> +E é por **isso** que é tão difícil escrever e raciocinar com precisão sobre o código JS assíncrono com retornos de chamada: porque não é assim que o nosso planejamento cerebral funciona.
```suggestion
E é por **isso** que é tão difícil escrever e raciocinar com precisão sobre o código JS assíncrono com callbacks: porque não é assim que o nosso planejamento cerebral funciona.
```

2020-08-13 01:28 UTC, gabsprates commented on async & performance/ch2.md
> +**Nota:** A única coisa pior do que não saber por que algum código quebra é não saber por que ele funcionou em primeiro lugar! É a mentalidade clássica do "castelo de cartas": "funciona, mas não sei
```suggestion
**Nota:** A única coisa pior do que não saber por que algum código quebra é, primeiramente, não saber por que ele funcionou! É a mentalidade clássica do "castelo de cartas": "funciona, mas não sei por quê, então ninguém toca!" Você pode ter ouvido: "O inferno são os outros" (Sartre), e o meme da reviravolta do programador: "O inferno é o código de outras pessoas". Eu acredito verdadeiramente que: "O inferno é não entender meu próprio código". E os callbacks são um dos principais culpados.
```

2020-08-13 21:48 UTC, nielvag commented
> Demorei bastante pra me organizar e terminar esse, perdão.
> Consegui! sweat_smile

Sem problemas!
As correções foram ótimas, obrigado!

2020-08-15 01:37 UTC, gabsprates approved these changes

2020-08-15 01:37 UTC, gabsprates commented
Muito bom! Teu nome já está na nossa lista de colaboradores? 🤔

2020-08-15 01:37 UTC, merged

2020-08-15 01:46 UTC, gabsprates commented
@all-contributors please add @nielvag for translation