this & object prototype: modelos mentais comparados
cez-aug/You-Dont-Know-JS pull request #341
Opened 2020-07-04 00:09 UTC by gabsprates

# Antes de enviar seu Pull Request

Faça o check abaixo para ver se o PR está no melhor padrão possível. 
Note que o conteúdo enviado será revisado antes de ser aceito, em geral blocos maiores de tradução levarão mais tempo
para serem aceitos (veja #68). A qualidade do material é um compromisso nosso.

- [x] Verifique se os jargões estão coerentes com o [WORDREFERENCE](WORDREFERENCE.md)
- [x] Revise a tradução com carinho :two_hearts: -- seu nome constará na parte que você traduziu.
- [x] Certifique-se que a `branch` de sua tradução contém as últimas atualizações da branch `portuguese-translation` do repositório principal.
- [x] Ao terminar sua parte da tradução, faça um Pull `Request` para o `branch` `portuguese-translation`. 
- [x] Caso o `Pull Request` for o último (finalização de capítulo), use o número da `issue` como referência e faça uso [dessas keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

2020-09-17 12:11 UTC, victorpothin commented on this & object prototypes/ch6.md
> +Agora, vamos implementar **exatamente a memsa funcionalidade** usando o estilo de código *OLOO*:
memsa -> mesma, pequeno erro de digitação :) tranquilex de acertar, muito bom!

2020-09-17 12:14 UTC, victorpothin requested changes
Há um pequeno erro de digitação, o restante está super OK! :)

2020-09-26 13:56 UTC, gabsprates commented
♻️ @victorpothin 

Olha de novo, por favor?

2020-10-01 00:27 UTC, victorpothin commented
> ♻️ @victorpothin
> 
> Olha de novo, por favor?

Claro, olhei e está OK! :)

2020-10-01 00:28 UTC, victorpothin approved these changes

2020-10-01 02:48 UTC, merged