this & object prototype: classes vs objetos - classes
cez-aug/You-Dont-Know-JS pull request #343
Opened 2020-07-21 00:04 UTC by gabsprates

# Antes de enviar seu Pull Request

Faça o check abaixo para ver se o PR está no melhor padrão possível. 
Note que o conteúdo enviado será revisado antes de ser aceito, em geral blocos maiores de tradução levarão mais tempo
para serem aceitos (veja #68). A qualidade do material é um compromisso nosso.

- [x] Verifique se os jargões estão coerentes com o [WORDREFERENCE](WORDREFERENCE.md)
- [x] Revise a tradução com carinho :two_hearts: -- seu nome constará na parte que você traduziu.
- [x] Certifique-se que a `branch` de sua tradução contém as últimas atualizações da branch `portuguese-translation` do repositório principal.
- [x] Ao terminar sua parte da tradução, faça um Pull `Request` para o `branch` `portuguese-translation`. 
- [x] Caso o `Pull Request` for o último (finalização de capítulo), use o número da `issue` como referência e faça uso [dessas keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

2020-09-17 12:19 UTC, victorpothin commented on this & object prototypes/ch6.md
> +Apesar das melhorias sintáticas, **essas não são classes *reais***, uma vez que elas ainda operam sobre o mecanismo do `[[Prototype]]`. Eles sofrem das mesmas discrepâncias de modelo mental que explo
sintaxxe -> sintaxe

2020-09-17 12:20 UTC, victorpothin requested changes
Um pequeno erro de digitação. O restante está super ótimo.

2020-09-26 14:03 UTC, gabsprates commented
♻️ @victorpothin,

Olha de novo, por favor?

2020-10-01 00:23 UTC, victorpothin commented
> ♻️ @victorpothin,
> 
> Olha de novo, por favor?

Perfeito!

2020-10-01 00:24 UTC, victorpothin approved these changes

2020-10-01 02:51 UTC, merged