Para manter o hoisting consistente! Corrigido exemplo no escopo do callback.
cez-aug/You-Dont-Know-JS pull request #365
Opened 2023-03-10 11:42 UTC by chen-zhenn

# Antes de enviar seu Pull Request

Faça o check abaixo para ver se o PR está no melhor padrão possível. 
Note que o conteúdo enviado será revisado antes de ser aceito, em geral blocos maiores de tradução levarão mais tempo
para serem aceitos (veja #68). A qualidade do material é um compromisso nosso.

- [ ] Verifique se os jargões estão coerentes com o [WORDREFERENCE](WORDREFERENCE.md)
- [ ] Revise a tradução com carinho :two_hearts: -- seu nome constará na parte que você traduziu.
- [x] Certifique-se que a `branch` de sua tradução contém as últimas atualizações da branch `portuguese-translation` do repositório principal.
- [x] Ao terminar sua parte da tradução, faça um Pull `Request` para o `branch` `portuguese-translation`. 
- [ ] Caso o `Pull Request` for o último (finalização de capítulo), use o número da `issue` como referência e faça uso [dessas keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

2023-03-15 02:17 UTC, nltncsr requested changes
Apenas um pequeno errinho ali mas fora isso foi bacana a renomeação :)

```diff
- Signficado
+ Significado
```

2023-03-16 00:18 UTC, chen-zhenn commented
> Apenas um pequeno errinho ali mas fora isso foi bacana a renomeação :)
> 
> ```diff
> - Signficado
> + Significado
> ```

2023-03-16 00:19 UTC, chen-zhenn commented
> Apenas um pequeno errinho ali mas fora isso foi bacana a renomeação :)
> 
> ```diff
> - Signficado
> + Significado
> ```

Não entendi man?

2023-03-17 19:09 UTC, GilbertoSVN commented
> > Apenas um pequeno errinho ali mas fora isso foi bacana a renomeação :)
> > ```diff
> > - Signficado
> > + Significado
> > ```
> 
> Desculpe man, mas não entendi sua colocação!

Ele quis mostrar que na parte do console.log, existe um erro de português:
![image](https://user-images.githubusercontent.com/36732280/225996937-4c307ac1-87d6-4da6-a69a-0133d0492947.png)
Ai sugeriu alterar do Signficado para Significado.

2023-05-12 18:08 UTC, MullerHub approved these changes

2025-03-02 18:23 UTC, closed without merging